In [1]:
from IPython.display import display, HTML

display(HTML("""
<style>

/* =========================
전체 레이아웃
========================= */

div.container{
    width:85% !important;
}

div.cell.code_cell.rendered{
    width:100%;
}

div.input_prompt{
    padding:0;
}

div.prompt{
    min-width:70px;
}

div#toc-wrapper{
    padding-top:120px;
}

table.dataframe{
    font-size:12px;
}

/* =========================
   코드 입력창
========================= */

div.CodeMirror{
    font-family:"마루 부리OTF 중간" !important;
    font-size:12pt !important;
    line-height:1.6;
}

/* =========================
   입력 셀
========================= */

div.input{
    font-family:"마루 부리OTF 중간" !important;
    font-size:12pt !important;
}

/* =========================
   코드 출력
========================= */

div.output{
    font-family:"마루 부리OTF 중간" !important;
    font-size:12pt !important;
}

/* =========================
   Markdown 전체
========================= */

.rendered_html{
    font-family:"마루 부리OTF 중간" !important;
    font-size:18px !important;
    line-height:1.8;
}

/* 제목 */

.rendered_html h1,
.rendered_html h2,
.rendered_html h3,
.rendered_html h4,
.rendered_html h5,
.rendered_html h6{
    font-family:"마루 부리OTF 조금굵은" !important;
}

/* 본문 */

.rendered_html p{
    font-family:"마루 부리OTF 중간" !important;
}

/* 리스트 */

.rendered_html li{
    font-family:"마루 부리OTF 중간" !important;
    padding:5px;
}

/* 인용 */

.rendered_html blockquote{
    font-family:"마루 부리OTF 중간" !important;
}

/* 표 */

.rendered_html table{
    font-family:"마루 부리OTF 중간" !important;
}

/* 코드 블록 */

.rendered_html pre,
.rendered_html code{
    font-family:"Consolas" !important;
    font-size:12pt !important;
}

</style>
"""))

In [2]:
import pandas as pd

In [3]:
# 데이터 수집 및 확인
store = pd.read_csv("./data/독립변수1_서울시 상권분석서비스(점포-상권)_2025년.csv", encoding="cp949")
change = pd.read_csv("./data/독립변수2_서울시 상권분석서비스(상권변화지표-상권).csv", encoding="cp949")
sales2023 = pd.read_csv("./data/독립변수3_2023년 서울시_상권분석서비스(추정매출-상권).csv", encoding="cp949")
sales2024 = pd.read_csv("./data/독립변수3_2024년 서울시 상권분석서비스(추정매출-상권).csv", encoding="cp949")
sales2025 = pd.read_csv("./data/독립변수3_2025년 서울시 상권분석서비스(추정매출-상권).csv", encoding="cp949")
sales_bg = pd.read_csv("./data/독립변수3_선택_서울시 상권분석서비스(추정매출-상권배후지)_2025년.csv", encoding="cp949")
floating = pd.read_csv("./data/독립변수4_ 서울시 상권분석서비스(길단위인구-상권).csv", encoding="cp949")
resident_trade = pd.read_csv("./data/독립변수5_ 서울시 상권분석서비스(상주인구-상권).csv", encoding="cp949")
resident_bg = pd.read_csv("./data/독립변수6_서울시 상권분석서비스(상주인구-상권배후지).csv", encoding="cp949")
resident_seoul = pd.read_csv("./data/독립변수7_서울시 상권분석서비스(상주인구-서울시).csv", encoding="cp949")
resident_gu = pd.read_csv("./data/독립변수8_서울시 상권분석서비스(상주인구-자치구).csv", encoding="cp949")
resident_dong = pd.read_csv("./data/독립변수9_서울시 상권분석서비스(상주인구-행정동).csv", encoding="cp949")
area = pd.read_csv("./data/독립변수10_서울시 상권분석서비스(영역-상권).csv", encoding="cp949")

# 데이터 크기 확인
print("점포-상권 :", store.shape)
print("상권변화지표-상권 :", change.shape)
print("2023년 추정매출-상권 :", sales2023.shape)
print("2024년 추정매출-상권 :", sales2024.shape)
print("2025년 추정매출-상권 :", sales2025.shape)
print("추정매출-상권배후지 :", sales_bg.shape)
print("길단위인구-상권 :", floating.shape)
print("상주인구-상권 :", resident_trade.shape)
print("상주인구-상권배후지 :", resident_bg.shape)
print("상주인구-서울시 :", resident_seoul.shape)
print("상주인구-자치구 :", resident_gu.shape)
print("상주인구-행정동 :", resident_dong.shape)
print("영역-상권 :", area.shape)

점포-상권 : (304775, 14)
상권변화지표-상권 : (36300, 11)
2023년 추정매출-상권 : (88246, 55)
2024년 추정매출-상권 : (87179, 55)
2025년 추정매출-상권 : (85732, 55)
추정매출-상권배후지 : (147035, 55)
길단위인구-상권 : (36281, 27)
상주인구-상권 : (35908, 29)
상주인구-상권배후지 : (23980, 29)
상주인구-서울시 : (22, 27)
상주인구-자치구 : (550, 27)
상주인구-행정동 : (9350, 27)
영역-상권 : (1650, 11)

# 원본 보존
- 전처리하다 잘못 수정될 경우를 대비하여 원본을 먼저 복사.

In [4]:
# 원본 보존
store_clean = store.copy()
change_clean = change.copy()
sales_2023 = sales2023.copy()
sales_2024 = sales2024.copy()
sales_2025 = sales2025.copy()
sales_bg_clean = sales_bg.copy()
floating_clean = floating.copy()
resident_trade_clean = resident_trade.copy()
resident_bg_clean = resident_bg.copy()
resident_seoul_clean = resident_seoul.copy()
resident_gu_clean = resident_gu.copy()
resident_dong_clean = resident_dong.copy()
area_clean = area.copy()

In [5]:
# 중복 확인 및 처리
print("점포 데이터 중복 :", store_clean.duplicated().sum())
print("상권변화지표 중복 :", change_clean.duplicated().sum())
print("2023년 추정매출 중복 :", sales_2023.duplicated().sum())
print("2024년 추정매출 중복 :", sales_2024.duplicated().sum())
print("2025년 추정매출 중복 :", sales_2025.duplicated().sum())
print("상권배후지 중복 :", sales_bg_clean.duplicated().sum())
print("길단위인구-상권 중복 :", floating_clean.duplicated().sum())
print("상주인구-상권 중복 :", resident_trade_clean.duplicated().sum())
print("상주인구-상권배후지 중복 :", resident_bg_clean.duplicated().sum())
print("상주인구-서울시 중복 :", resident_seoul_clean.duplicated().sum())
print("상주인구-자치구 중복 :", resident_gu_clean.duplicated().sum())
print("상주인구-행정동 중복 :", resident_dong_clean.duplicated().sum())
print("영역-상권 중복 :", area_clean.duplicated().sum())

store_clean = store_clean.drop_duplicates()
change_clean = change_clean.drop_duplicates()
sales_2023 = sales_2023.drop_duplicates()
sales_2024 = sales_2024.drop_duplicates()
sales_2025 = sales_2025.drop_duplicates()
sales_bg_clean = sales_bg_clean.drop_duplicates()
floating_clean = floating_clean.drop_duplicates()
resident_trade_clean = resident_trade_clean.drop_duplicates()
resident_bg_clean = resident_bg_clean.drop_duplicates()
resident_seoul_clean = resident_seoul_clean.drop_duplicates()
resident_gu_clean = resident_gu_clean.drop_duplicates()
resident_dong_clean = resident_dong_clean.drop_duplicates()
area_clean = area_clean.drop_duplicates()

점포 데이터 중복 : 0
상권변화지표 중복 : 0
2023년 추정매출 중복 : 0
2024년 추정매출 중복 : 0
2025년 추정매출 중복 : 0
상권배후지 중복 : 0
길단위인구-상권 중복 : 0
상주인구-상권 중복 : 0
상주인구-상권배후지 중복 : 0
상주인구-서울시 중복 : 0
상주인구-자치구 중복 : 0
상주인구-행정동 중복 : 0
영역-상권 중복 : 0

# 컬럼명 표준화

In [6]:
# store 컬럼명 수정
store_clean = store_clean.rename(columns={
    'stdr_yyqu_cd': '기준년분기코드',
    'trdar_se_cd': '상권구분코드',
    'trdar_se_cd_nm': '상권구분코드명',
    'trdar_cd': '상권코드',
    'trdar_cd_nm': '상권코드명',
    'svc_induty_cd': '서비스업종코드',
    'svc_induty_cd_nm': '서비스업종코드명',
    'stor_co': '점포수',
    'similr_induty_stor_co': '유사업종점포수',
    'opbiz_rt': '개업률',
    'opbiz_stor_co': '개업점포수',
    'clsbiz_rt': '폐업률',
    'clsbiz_stor_co': '폐업점포수',
    'frc_stor_co': '프랜차이즈점포수'
})

In [7]:
# 모든 데이터프레임의 컬럼명을 한번에 수정하기
dfs = [
    change_clean,
    sales_2023,
    sales_2024,
    sales_2025,
    floating_clean,
    resident_trade_clean,
    resident_bg_clean,
    resident_seoul_clean,
    resident_gu_clean,
    resident_dong_clean,
    area_clean,
]

for df in dfs:
    df.columns = df.columns.str.replace(
        r'[^가-힣a-zA-Z0-9_]', '', regex=True )

In [8]:
for df in dfs:
    print(df.columns.tolist())

['기준년분기코드', '상권구분코드', '상권구분코드명', '상권코드', '상권코드명', '상권변화지표', '상권변화지표명', '운영영업개월평균', '폐업영업개월평균', '서울운영영업개월평균', '서울폐업영업개월평균']
['기준년분기코드', '상권구분코드', '상권구분코드명', '상권코드', '상권코드명', '서비스업종코드', '서비스업종코드명', '당월매출금액', '당월매출건수', '주중매출금액', '주말매출금액', '월요일매출금액', '화요일매출금액', '수요일매출금액', '목요일매출금액', '금요일매출금액', '토요일매출금액', '일요일매출금액', '시간대0006매출금액', '시간대0611매출금액', '시간대1114매출금액', '시간대1417매출금액', '시간대1721매출금액', '시간대2124매출금액', '남성매출금액', '여성매출금액', '연령대10매출금액', '연령대20매출금액', '연령대30매출금액', '연령대40매출금액', '연령대50매출금액', '연령대60이상매출금액', '주중매출건수', '주말매출건수', '월요일매출건수', '화요일매출건수', '수요일매출건수', '목요일매출건수', '금요일매출건수', '토요일매출건수', '일요일매출건수', '시간대건수06매출건수', '시간대건수11매출건수', '시간대건수14매출건수', '시간대건수17매출건수', '시간대건수21매출건수', '시간대건수24매출건수', '남성매출건수', '여성매출건수', '연령대10매출건수', '연령대20매출건수', '연령대30매출건수', '연령대40매출건수', '연령대50매출건수', '연령대60이상매출건수']
['기준년분기코드', '상권구분코드', '상권구분코드명', '상권코드', '상권코드명', '서비스업종코드', '서비스업종코드명', '당월매출금액', '당월매출건수', '주중매출금액', '주말매출금액', '월요일매출금액', '화요일매출금액', '수요일매출금액', '목요일매출금액', '금요일매출금액', '토요일매출금액', '일요일매출금액', '시간대0006매출금액', '시간대0611매출금액', '시간대1114매출금액', '시간대1417매출금액', '시간대1721매출금액', '시간대2124매출금액', '남성매출금액', '여성매출금액', '연령대10매출금액', '연령대20매출금액', '연령대30매출금액', '연령대40매출금액', '연령대50매출금액', '연령대60이상매출금액', '주중매출건수', '주말매출건수', '월요일매출건수', '화요일매출건수', '수요일매출건수', '목요일매출건수', '금요일매출건수', '토요일매출건수', '일요일매출건수', '시간대건수06매출건수', '시간대건수11매출건수', '시간대건수14매출건수', '시간대건수17매출건수', '시간대건수21매출건수', '시간대건수24매출건수', '남성매출건수', '여성매출건수', '연령대10매출건수', '연령대20매출건수', '연령대30매출건수', '연령대40매출건수', '연령대50매출건수', '연령대60이상매출건수']
['기준년분기코드', '상권구분코드', '상권구분코드명', '상권코드', '상권코드명', '서비스업종코드', '서비스업종코드명', '당월매출금액', '당월매출건수', '주중매출금액', '주말매출금액', '월요일매출금액', '화요일매출금액', '수요일매출금액', '목요일매출금액', '금요일매출금액', '토요일매출금액', '일요일매출금액', '시간대0006매출금액', '시간대0611매출금액', '시간대1114매출금액', '시간대1417매출금액', '시간대1721매출금액', '시간대2124매출금액', '남성매출금액', '여성매출금액', '연령대10매출금액', '연령대20매출금액', '연령대30매출금액', '연령대40매출금액', '연령대50매출금액', '연령대60이상매출금액', '주중매출건수', '주말매출건수', '월요일매출건수', '화요일매출건수', '수요일매출건수', '목요일매출건수', '금요일매출건수', '토요일매출건수', '일요일매출건수', '시간대건수06매출건수', '시간대건수11매출건수', '시간대건수14매출건수', '시간대건수17매출건수', '시간대건수21매출건수', '시간대건수24매출건수', '남성매출건수', '여성매출건수', '연령대10매출건수', '연령대20매출건수', '연령대30매출건수', '연령대40매출건수', '연령대50매출건수', '연령대60이상매출건수']
['기준년분기코드', '상권구분코드', '상권구분코드명', '상권코드', '상권코드명', '총유동인구수', '남성유동인구수', '여성유동인구수', '연령대10유동인구수', '연령대20유동인구수', '연령대30유동인구수', '연령대40유동인구수', '연령대50유동인구수', '연령대60이상유동인구수', '시간대0006유동인구수', '시간대0611유동인구수', '시간대1114유동인구수', '시간대1417유동인구수', '시간대1721유동인구수', '시간대2124유동인구수', '월요일유동인구수', '화요일유동인구수', '수요일유동인구수', '목요일유동인구수', '금요일유동인구수', '토요일유동인구수', '일요일유동인구수']
['기준년분기코드', '상권구분코드', '상권구분코드명', '상권코드', '상권코드명', '총상주인구수', '남성상주인구수', '여성상주인구수', '연령대10상주인구수', '연령대20상주인구수', '연령대30상주인구수', '연령대40상주인구수', '연령대50상주인구수', '연령대60이상상주인구수', '남성연령대10상주인구수', '남성연령대20상주인구수', '남성연령대30상주인구수', '남성연령대40상주인구수', '남성연령대50상주인구수', '남성연령대60이상상주인구수', '여성연령대10상주인구수', '여성연령대20상주인구수', '여성연령대30상주인구수', '여성연령대40상주인구수', '여성연령대50상주인구수', '여성연령대60이상상주인구수', '총가구수', '아파트가구수', '비아파트가구수']
['기준년분기코드', '상권구분코드', '상권구분코드명', '상권배후지코드', '상권배후지코드명', '총상주인구수', '남성상주인구수', '여성상주인구수', '연령대10상주인구수', '연령대20상주인구수', '연령대30상주인구수', '연령대40상주인구수', '연령대50상주인구수', '연령대60이상상주인구수', '남성연령대10상주인구수', '남성연령대20상주인구수', '남성연령대30상주인구수', '남성연령대40상주인구수', '남성연령대50상주인구수', '남성연령대60이상상주인구수', '여성연령대10상주인구수', '여성연령대20상주인구수', '여성연령대30상주인구수', '여성연령대40상주인구수', '여성연령대50상주인구수', '여성연령대60이상상주인구수', '총가구수', '아파트가구수', '비아파트가구수']
['기준년분기코드', '서울시코드', '서울시코드명', '총상주인구수', '남성상주인구수', '여성상주인구수', '연령대10상주인구수', '연령대20상주인구수', '연령대30상주인구수', '연령대40상주인구수', '연령대50상주인구수', '연령대60이상상주인구수', '남성연령대10상주인구수', '남성연령대20상주인구수', '남성연령대30상주인구수', '남성연령대40상주인구수', '남성연령대50상주인구수', '남성연령대60이상상주인구수', '여성연령대10상주인구수', '여성연령대20상주인구수', '여성연령대30상주인구수', '여성연령대40상주인구수', '여성연령대50상주인구수', '여성연령대60이상상주인구수', '총가구수', '아파트가구수', '비아파트가구수']
['기준년분기코드', '자치구코드', '자치구코드명', '총상주인구수', '남성상주인구수', '여성상주인구수', '연령대10상주인구수', '연령대20상주인구수', '연령대30상주인구수', '연령대40상주인구수', '연령대50상주인구수', '연령대60이상상주인구수', '남성연령대10상주인구수', '남성연령대20상주인구수', '남성연령대30상주인구수', '남성연령대40상주인구수', '남성연령대50상주인구수', '남성연령대60이상상주인구수', '여성연령대10상주인구수', '여성연령대20상주인구수', '여성연령대30상주인구수', '여성연령대40상주인구수', '여성연령대50상주인구수', '여성연령대60이상상주인구수', '총가구수', '아파트가구수', '비아파트가구수']
['기준년분기코드', '행정동코드', '행정동코드명', '총상주인구수', '남성상주인구수', '여성상주인구수', '연령대10상주인구수', '연령대20상주인구수', '연령대30상주인구수', '연령대40상주인구수', '연령대50상주인구수', '연령대60이상상주인구수', '남성연령대10상주인구수', '남성연령대20상주인구수', '남성연령대30상주인구수', '남성연령대40상주인구수', '남성연령대50상주인구수', '남성연령대60이상상주인구수', '여성연령대10상주인구수', '여성연령대20상주인구수', '여성연령대30상주인구수', '여성연령대40상주인구수', '여성연령대50상주인구수', '여성연령대60이상상주인구수', '총가구수', '아파트가구수', '비아파트가구수']
['상권구분코드', '상권구분코드명', '상권코드', '상권코드명', '엑스좌표값', '와이좌표값', '자치구코드', '자치구코드명', '행정동코드', '행정동코드명', '영역면적']

In [9]:
sales_bg_clean = sales_bg_clean.rename(columns={
    # 기본 정보
    'stdr_yyqu_cd': '기준년분기코드',
    'trdar_se_cd': '상권구분코드',
    'trdar_se_cd_nm': '상권구분코드명',
    'trdar_cd': '상권코드',
    'trdar_cd_nm': '상권코드명',
    'svc_induty_cd': '서비스업종코드',
    'svc_induty_cd_nm': '서비스업종코드명',

    # 전체 매출
    'thsmon_selng_amt': '당월매출금액',
    'thsmon_selng_co': '당월매출건수',

    # 주중 / 주말 매출금액
    'mdwk_selng_amt': '주중매출금액',
    'wkend_selng_amt': '주말매출금액',

    # 요일별 매출금액
    'mon_selng_amt': '월요일매출금액',
    'tues_selng_amt': '화요일매출금액',
    'wed_selng_amt': '수요일매출금액',
    'thur_selng_amt': '목요일매출금액',
    'fri_selng_amt': '금요일매출금액',
    'sat_selng_amt': '토요일매출금액',
    'sun_selng_amt': '일요일매출금액',

    # 시간대별 매출금액
    'tmzon_00_06_selng_amt': '시간대00~06매출금액',
    'tmzon_06_11_selng_amt': '시간대06~11매출금액',
    'tmzon_11_14_selng_amt': '시간대11~14매출금액',
    'tmzon_14_17_selng_amt': '시간대14~17매출금액',
    'tmzon_17_21_selng_amt': '시간대17~21매출금액',
    'tmzon_21_24_selng_amt': '시간대21~24매출금액',

    # 성별 매출금액
    'ml_selng_amt': '남성매출금액',
    'fml_selng_amt': '여성매출금액',

    # 연령대별 매출금액
    'agrde_10_selng_amt': '연령대10매출금액',
    'agrde_20_selng_amt': '연령대20매출금액',
    'agrde_30_selng_amt': '연령대30매출금액',
    'agrde_40_selng_amt': '연령대40매출금액',
    'agrde_50_selng_amt': '연령대50매출금액',
    'agrde_60_above_selng_amt': '연령대60이상매출금액',

    # 주중 / 주말 매출건수
    'mdwk_selng_co': '주중매출건수',
    'wkend_selng_co': '주말매출건수',

    # 요일별 매출건수
    'mon_selng_co': '월요일매출건수',
    'tues_selng_co': '화요일매출건수',
    'wed_selng_co': '수요일매출건수',
    'thur_selng_co': '목요일매출건수',
    'fri_selng_co': '금요일매출건수',
    'sat_selng_co': '토요일매출건수',
    'sun_selng_co': '일요일매출건수',

    # 시간대별 매출건수
    'tmzon_00_06_selng_co': '시간대00~06매출건수',
    'tmzon_06_11_selng_co': '시간대06~11매출건수',
    'tmzon_11_14_selng_co': '시간대11~14매출건수',
    'tmzon_14_17_selng_co': '시간대14~17매출건수',
    'tmzon_17_21_selng_co': '시간대17~21매출건수',
    'tmzon_21_24_selng_co': '시간대21~24매출건수',

    # 성별 매출건수
    'ml_selng_co': '남성매출건수',
    'fml_selng_co': '여성매출건수',

    # 연령대별 매출건수
    'agrde_10_selng_co': '연령대10매출건수',
    'agrde_20_selng_co': '연령대20매출건수',
    'agrde_30_selng_co': '연령대30매출건수',
    'agrde_40_selng_co': '연령대40매출건수',
    'agrde_50_selng_co': '연령대50매출건수',
    'agrde_60_above_selng_co': '연령대60이상매출건수'
})

In [10]:
print("=== 점포-상권 ===")
print(store_clean.columns.tolist())

print("\n=== 상권변화지표-상권 ===")
print(change_clean.columns.tolist())

print("\n=== 2023년-추정매출-상권 ===")
print(sales_2023.columns.tolist())

print("\n=== 2024년-추정매출-상권 ===")
print(sales_2024.columns.tolist())

print("\n=== 2025년-추정매출-상권 ===")
print(sales_2025.columns.tolist())

print("\n=== 추정매출-상권배후지 ===")
print(sales_bg_clean.columns.tolist())

print("\n=== 길단위인구-상권 ===")
print(floating_clean.columns.tolist())

print("\n=== 상주인구-상권 ===")
print(resident_trade_clean.columns.tolist())

print("\n=== 상주인구-상권배후지 ===")
print(resident_bg_clean.columns.tolist())

print("\n=== 상주인구-서울시 ===")
print(resident_seoul_clean.columns.tolist())

print("\n=== 상주인구-자치구 ===")
print(resident_gu_clean.columns.tolist())

print("\n=== 상주인구-행정동 ===")
print(resident_dong_clean.columns.tolist())

print("\n=== 영역-상권 ===")
print(area_clean.columns.tolist())

=== 점포-상권 ===
['기준년분기코드', '상권구분코드', '상권구분코드명', '상권코드', '상권코드명', '서비스업종코드', '서비스업종코드명', '점포수', '유사업종점포수', '개업률', '개업점포수', '폐업률', '폐업점포수', '프랜차이즈점포수']

=== 상권변화지표-상권 ===
['기준년분기코드', '상권구분코드', '상권구분코드명', '상권코드', '상권코드명', '상권변화지표', '상권변화지표명', '운영영업개월평균', '폐업영업개월평균', '서울운영영업개월평균', '서울폐업영업개월평균']

=== 2023년-추정매출-상권 ===
['기준년분기코드', '상권구분코드', '상권구분코드명', '상권코드', '상권코드명', '서비스업종코드', '서비스업종코드명', '당월매출금액', '당월매출건수', '주중매출금액', '주말매출금액', '월요일매출금액', '화요일매출금액', '수요일매출금액', '목요일매출금액', '금요일매출금액', '토요일매출금액', '일요일매출금액', '시간대0006매출금액', '시간대0611매출금액', '시간대1114매출금액', '시간대1417매출금액', '시간대1721매출금액', '시간대2124매출금액', '남성매출금액', '여성매출금액', '연령대10매출금액', '연령대20매출금액', '연령대30매출금액', '연령대40매출금액', '연령대50매출금액', '연령대60이상매출금액', '주중매출건수', '주말매출건수', '월요일매출건수', '화요일매출건수', '수요일매출건수', '목요일매출건수', '금요일매출건수', '토요일매출건수', '일요일매출건수', '시간대건수06매출건수', '시간대건수11매출건수', '시간대건수14매출건수', '시간대건수17매출건수', '시간대건수21매출건수', '시간대건수24매출건수', '남성매출건수', '여성매출건수', '연령대10매출건수', '연령대20매출건수', '연령대30매출건수', '연령대40매출건수', '연령대50매출건수', '연령대60이상매출건수']

=== 2024년-추정매출-상권 ===
['기준년분기코드', '상권구분코드', '상권구분코드명', '상권코드', '상권코드명', '서비스업종코드', '서비스업종코드명', '당월매출금액', '당월매출건수', '주중매출금액', '주말매출금액', '월요일매출금액', '화요일매출금액', '수요일매출금액', '목요일매출금액', '금요일매출금액', '토요일매출금액', '일요일매출금액', '시간대0006매출금액', '시간대0611매출금액', '시간대1114매출금액', '시간대1417매출금액', '시간대1721매출금액', '시간대2124매출금액', '남성매출금액', '여성매출금액', '연령대10매출금액', '연령대20매출금액', '연령대30매출금액', '연령대40매출금액', '연령대50매출금액', '연령대60이상매출금액', '주중매출건수', '주말매출건수', '월요일매출건수', '화요일매출건수', '수요일매출건수', '목요일매출건수', '금요일매출건수', '토요일매출건수', '일요일매출건수', '시간대건수06매출건수', '시간대건수11매출건수', '시간대건수14매출건수', '시간대건수17매출건수', '시간대건수21매출건수', '시간대건수24매출건수', '남성매출건수', '여성매출건수', '연령대10매출건수', '연령대20매출건수', '연령대30매출건수', '연령대40매출건수', '연령대50매출건수', '연령대60이상매출건수']

=== 2025년-추정매출-상권 ===
['기준년분기코드', '상권구분코드', '상권구분코드명', '상권코드', '상권코드명', '서비스업종코드', '서비스업종코드명', '당월매출금액', '당월매출건수', '주중매출금액', '주말매출금액', '월요일매출금액', '화요일매출금액', '수요일매출금액', '목요일매출금액', '금요일매출금액', '토요일매출금액', '일요일매출금액', '시간대0006매출금액', '시간대0611매출금액', '시간대1114매출금액', '시간대1417매출금액', '시간대1721매출금액', '시간대2124매출금액', '남성매출금액', '여성매출금액', '연령대10매출금액', '연령대20매출금액', '연령대30매출금액', '연령대40매출금액', '연령대50매출금액', '연령대60이상매출금액', '주중매출건수', '주말매출건수', '월요일매출건수', '화요일매출건수', '수요일매출건수', '목요일매출건수', '금요일매출건수', '토요일매출건수', '일요일매출건수', '시간대건수06매출건수', '시간대건수11매출건수', '시간대건수14매출건수', '시간대건수17매출건수', '시간대건수21매출건수', '시간대건수24매출건수', '남성매출건수', '여성매출건수', '연령대10매출건수', '연령대20매출건수', '연령대30매출건수', '연령대40매출건수', '연령대50매출건수', '연령대60이상매출건수']

=== 추정매출-상권배후지 ===
['기준년분기코드', '상권구분코드', '상권구분코드명', '상권코드', '상권코드명', '서비스업종코드', '서비스업종코드명', '당월매출금액', '당월매출건수', '주중매출금액', '주말매출금액', '월요일매출금액', '화요일매출금액', '수요일매출금액', '목요일매출금액', '금요일매출금액', '토요일매출금액', '일요일매출금액', '시간대00~06매출금액', '시간대06~11매출금액', '시간대11~14매출금액', '시간대14~17매출금액', '시간대17~21매출금액', '시간대21~24매출금액', '남성매출금액', '여성매출금액', '연령대10매출금액', '연령대20매출금액', '연령대30매출금액', '연령대40매출금액', '연령대50매출금액', '연령대60이상매출금액', '주중매출건수', '주말매출건수', '월요일매출건수', '화요일매출건수', '수요일매출건수', '목요일매출건수', '금요일매출건수', '토요일매출건수', '일요일매출건수', '시간대00~06매출건수', '시간대06~11매출건수', '시간대11~14매출건수', '시간대14~17매출건수', '시간대17~21매출건수', '시간대21~24매출건수', '남성매출건수', '여성매출건수', '연령대10매출건수', '연령대20매출건수', '연령대30매출건수', '연령대40매출건수', '연령대50매출건수', '연령대60이상매출건수']

=== 길단위인구-상권 ===
['기준년분기코드', '상권구분코드', '상권구분코드명', '상권코드', '상권코드명', '총유동인구수', '남성유동인구수', '여성유동인구수', '연령대10유동인구수', '연령대20유동인구수', '연령대30유동인구수', '연령대40유동인구수', '연령대50유동인구수', '연령대60이상유동인구수', '시간대0006유동인구수', '시간대0611유동인구수', '시간대1114유동인구수', '시간대1417유동인구수', '시간대1721유동인구수', '시간대2124유동인구수', '월요일유동인구수', '화요일유동인구수', '수요일유동인구수', '목요일유동인구수', '금요일유동인구수', '토요일유동인구수', '일요일유동인구수']

=== 상주인구-상권 ===
['기준년분기코드', '상권구분코드', '상권구분코드명', '상권코드', '상권코드명', '총상주인구수', '남성상주인구수', '여성상주인구수', '연령대10상주인구수', '연령대20상주인구수', '연령대30상주인구수', '연령대40상주인구수', '연령대50상주인구수', '연령대60이상상주인구수', '남성연령대10상주인구수', '남성연령대20상주인구수', '남성연령대30상주인구수', '남성연령대40상주인구수', '남성연령대50상주인구수', '남성연령대60이상상주인구수', '여성연령대10상주인구수', '여성연령대20상주인구수', '여성연령대30상주인구수', '여성연령대40상주인구수', '여성연령대50상주인구수', '여성연령대60이상상주인구수', '총가구수', '아파트가구수', '비아파트가구수']

=== 상주인구-상권배후지 ===
['기준년분기코드', '상권구분코드', '상권구분코드명', '상권배후지코드', '상권배후지코드명', '총상주인구수', '남성상주인구수', '여성상주인구수', '연령대10상주인구수', '연령대20상주인구수', '연령대30상주인구수', '연령대40상주인구수', '연령대50상주인구수', '연령대60이상상주인구수', '남성연령대10상주인구수', '남성연령대20상주인구수', '남성연령대30상주인구수', '남성연령대40상주인구수', '남성연령대50상주인구수', '남성연령대60이상상주인구수', '여성연령대10상주인구수', '여성연령대20상주인구수', '여성연령대30상주인구수', '여성연령대40상주인구수', '여성연령대50상주인구수', '여성연령대60이상상주인구수', '총가구수', '아파트가구수', '비아파트가구수']

=== 상주인구-서울시 ===
['기준년분기코드', '서울시코드', '서울시코드명', '총상주인구수', '남성상주인구수', '여성상주인구수', '연령대10상주인구수', '연령대20상주인구수', '연령대30상주인구수', '연령대40상주인구수', '연령대50상주인구수', '연령대60이상상주인구수', '남성연령대10상주인구수', '남성연령대20상주인구수', '남성연령대30상주인구수', '남성연령대40상주인구수', '남성연령대50상주인구수', '남성연령대60이상상주인구수', '여성연령대10상주인구수', '여성연령대20상주인구수', '여성연령대30상주인구수', '여성연령대40상주인구수', '여성연령대50상주인구수', '여성연령대60이상상주인구수', '총가구수', '아파트가구수', '비아파트가구수']

=== 상주인구-자치구 ===
['기준년분기코드', '자치구코드', '자치구코드명', '총상주인구수', '남성상주인구수', '여성상주인구수', '연령대10상주인구수', '연령대20상주인구수', '연령대30상주인구수', '연령대40상주인구수', '연령대50상주인구수', '연령대60이상상주인구수', '남성연령대10상주인구수', '남성연령대20상주인구수', '남성연령대30상주인구수', '남성연령대40상주인구수', '남성연령대50상주인구수', '남성연령대60이상상주인구수', '여성연령대10상주인구수', '여성연령대20상주인구수', '여성연령대30상주인구수', '여성연령대40상주인구수', '여성연령대50상주인구수', '여성연령대60이상상주인구수', '총가구수', '아파트가구수', '비아파트가구수']

=== 상주인구-행정동 ===
['기준년분기코드', '행정동코드', '행정동코드명', '총상주인구수', '남성상주인구수', '여성상주인구수', '연령대10상주인구수', '연령대20상주인구수', '연령대30상주인구수', '연령대40상주인구수', '연령대50상주인구수', '연령대60이상상주인구수', '남성연령대10상주인구수', '남성연령대20상주인구수', '남성연령대30상주인구수', '남성연령대40상주인구수', '남성연령대50상주인구수', '남성연령대60이상상주인구수', '여성연령대10상주인구수', '여성연령대20상주인구수', '여성연령대30상주인구수', '여성연령대40상주인구수', '여성연령대50상주인구수', '여성연령대60이상상주인구수', '총가구수', '아파트가구수', '비아파트가구수']

=== 영역-상권 ===
['상권구분코드', '상권구분코드명', '상권코드', '상권코드명', '엑스좌표값', '와이좌표값', '자치구코드', '자치구코드명', '행정동코드', '행정동코드명', '영역면적']

# 자료형 확인 및 통일

In [11]:
# 병합에 사용할 주요 컬럼 자료형 확인

print("=== 점포-상권 ===")
print(store_clean[
    ['기준년분기코드', '상권코드', '서비스업종코드']
].dtypes)

print("\n=== 상권변화지표-상권 ===")
print(change_clean[
    ['기준년분기코드', '상권코드']
].dtypes)

print("\n=== 2023년-추정매출-상권 ===")
print(sales_2023[
    ['기준년분기코드', '상권코드', '서비스업종코드']
].dtypes)

print("\n=== 2024년-추정매출-상권 ===")
print(sales_2024[
    ['기준년분기코드', '상권코드', '서비스업종코드']
].dtypes)

print("\n=== 2025년-추정매출-상권 ===")
print(sales_2025[
    ['기준년분기코드', '상권코드', '서비스업종코드']
].dtypes)

print("\n=== 추정매출-상권배후지 ===")
print(sales_bg_clean[
    ['기준년분기코드', '상권코드', '서비스업종코드']
].dtypes)

print("\n=== 길단위인구-상권 ===")
print(floating_clean[
    ['기준년분기코드', '상권코드']
].dtypes)

print("\n=== 상주인구-상권 ===")
print(resident_trade_clean[
    ['기준년분기코드', '상권코드']
].dtypes)

print("\n=== 상주인구-상권배후지 ===")
print(resident_bg_clean[
    ['기준년분기코드', '상권배후지코드']
].dtypes)

print("\n=== 상주인구-서울시 ===")
print(resident_seoul_clean[
    ['기준년분기코드', '서울시코드']
].dtypes)

print("\n=== 상주인구-자치구 ===")
print(resident_gu_clean[
    ['기준년분기코드', '자치구코드']
].dtypes)

print("\n=== 상주인구-행정동 ===")
print(resident_dong_clean[
    ['기준년분기코드', '행정동코드']
].dtypes)

print("\n=== 영역-상권 ===")
print(area_clean[
    ['상권코드', '자치구코드', '행정동코드']
].dtypes)

=== 점포-상권 ===
기준년분기코드     int64
상권코드        int64
서비스업종코드    object
dtype: object

=== 상권변화지표-상권 ===
기준년분기코드    int64
상권코드       int64
dtype: object

=== 2023년-추정매출-상권 ===
기준년분기코드     int64
상권코드        int64
서비스업종코드    object
dtype: object

=== 2024년-추정매출-상권 ===
기준년분기코드     int64
상권코드        int64
서비스업종코드    object
dtype: object

=== 2025년-추정매출-상권 ===
기준년분기코드     int64
상권코드        int64
서비스업종코드    object
dtype: object

=== 추정매출-상권배후지 ===
기준년분기코드     int64
상권코드        int64
서비스업종코드    object
dtype: object

=== 길단위인구-상권 ===
기준년분기코드    int64
상권코드       int64
dtype: object

=== 상주인구-상권 ===
기준년분기코드    int64
상권코드       int64
dtype: object

=== 상주인구-상권배후지 ===
기준년분기코드    int64
상권배후지코드    int64
dtype: object

=== 상주인구-서울시 ===
기준년분기코드    int64
서울시코드      int64
dtype: object

=== 상주인구-자치구 ===
기준년분기코드    int64
자치구코드      int64
dtype: object

=== 상주인구-행정동 ===
기준년분기코드    int64
행정동코드      int64
dtype: object

=== 영역-상권 ===
상권코드     int64
자치구코드    int64
행정동코드    int64
dtype: object

In [12]:
# change는 서비스업종 컬럼 자체가 없으므로 -> 기준년분기코드, 상권코드만 결합하는 구조로 확인
print(store_clean[['기준년분기코드','상권코드']].dtypes)
print(change_clean[['기준년분기코드','상권코드']].dtypes)
print(sales_2023[['기준년분기코드','상권코드']].dtypes)
print(sales_2024[['기준년분기코드','상권코드']].dtypes)
print(sales_2025[['기준년분기코드','상권코드']].dtypes)
print(sales_bg_clean[['기준년분기코드','상권코드']].dtypes)

# 길단위인구, 상주인구-상권은 기준년분기코드 + 상권코드로 결합 가능
print(floating_clean[['기준년분기코드','상권코드']].dtypes)
print(resident_trade_clean[['기준년분기코드','상권코드']].dtypes)

# 나머지 데이터는 공간 단위가 달라 각 데이터의 고유 코드 기준으로 확인
print(resident_bg_clean[['기준년분기코드','상권배후지코드']].dtypes)
print(resident_seoul_clean[['기준년분기코드','서울시코드']].dtypes)
print(resident_gu_clean[['기준년분기코드','자치구코드']].dtypes)
print(resident_dong_clean[['기준년분기코드','행정동코드']].dtypes)
print(area_clean[['상권코드','자치구코드','행정동코드']].dtypes)

기준년분기코드    int64
상권코드       int64
dtype: object
기준년분기코드    int64
상권코드       int64
dtype: object
기준년분기코드    int64
상권코드       int64
dtype: object
기준년분기코드    int64
상권코드       int64
dtype: object
기준년분기코드    int64
상권코드       int64
dtype: object
기준년분기코드    int64
상권코드       int64
dtype: object
기준년분기코드    int64
상권코드       int64
dtype: object
기준년분기코드    int64
상권코드       int64
dtype: object
기준년분기코드    int64
상권배후지코드    int64
dtype: object
기준년분기코드    int64
서울시코드      int64
dtype: object
기준년분기코드    int64
자치구코드      int64
dtype: object
기준년분기코드    int64
행정동코드      int64
dtype: object
상권코드     int64
자치구코드    int64
행정동코드    int64
dtype: object

# 중복값 확인 및 처리

In [13]:
# 중복값 확인
print("점포-상권:", store_clean.duplicated().sum())
print("상권변화지표-상권:", change_clean.duplicated().sum())
print("2023년-추정매출-상권:", sales_2023.duplicated().sum())
print("2024년-추정매출-상권:", sales_2024.duplicated().sum())
print("2025년-추정매출-상권:", sales_2025.duplicated().sum())
print("추정매출-상권배후지:", sales_bg_clean.duplicated().sum())
print("길단위인구-상권:", floating_clean.duplicated().sum())
print("상주인구-상권:", resident_trade_clean.duplicated().sum())
print("상주인구-상권배후지:", resident_bg_clean.duplicated().sum())
print("상주인구-서울시:", resident_seoul_clean.duplicated().sum())
print("상주인구-자치구:", resident_gu_clean.duplicated().sum())
print("상주인구-행정동:", resident_dong_clean.duplicated().sum())
print("영역-상권:", area_clean.duplicated().sum())

점포-상권: 0
상권변화지표-상권: 0
2023년-추정매출-상권: 0
2024년-추정매출-상권: 0
2025년-추정매출-상권: 0
추정매출-상권배후지: 0
길단위인구-상권: 0
상주인구-상권: 0
상주인구-상권배후지: 0
상주인구-서울시: 0
상주인구-자치구: 0
상주인구-행정동: 0
영역-상권: 0

In [14]:
# 중복이 존재할 때만
# store_clean = store_clean.drop_duplicates()
# change_clean = change_cleann.drop_duplicates()
# sales_2023 = sales_2023.drop_duplicates()
# sales_2024 = sales_2024.drop_duplicates()
# sales_2025 = sales_2025.drop_duplicates()
# sales_bg_clean = sales_bg_clean.drop_duplicates()
# floating_clean = floating_clean.drop_duplicates()
# resident_trade_clean = resident_trade_clean.drop_duplicates()
# resident_bg_clean = resident_bg_clean.drop_duplicates()
# resident_seoul_clean = resident_seoul_clean.drop_duplicates()
# resident_gu_clean = resident_gu_clean.drop_duplicates()
# resident_dong_clean = resident_dong_clean.drop_duplicates()
# area_clean = area_clean.drop_duplicates()

# 결측치 확인 및 처리

In [15]:
# 결측치 확인 및 처리
def missing_check(df):
    result = pd.DataFrame({
        "결측치": df.isnull().sum(),
        "결측률(%)": (df.isnull().mean() * 100).round(2)
    })

    return result[result["결측치"] > 0]

display(missing_check(store_clean))
display(missing_check(change_clean))
display(missing_check(sales_2023))
display(missing_check(sales_2024))
display(missing_check(sales_2025))
display(missing_check(sales_bg_clean))
display(missing_check(floating_clean))
display(missing_check(resident_trade_clean))
display(missing_check(resident_bg_clean))
display(missing_check(resident_seoul_clean))
display(missing_check(resident_gu_clean))
display(missing_check(resident_dong_clean))
display(missing_check(area_clean))

Empty DataFrame
Columns: [결측치, 결측률(%)]
Index: []

Empty DataFrame
Columns: [결측치, 결측률(%)]
Index: []

Empty DataFrame
Columns: [결측치, 결측률(%)]
Index: []

Empty DataFrame
Columns: [결측치, 결측률(%)]
Index: []

Empty DataFrame
Columns: [결측치, 결측률(%)]
Index: []

Empty DataFrame
Columns: [결측치, 결측률(%)]
Index: []

Empty DataFrame
Columns: [결측치, 결측률(%)]
Index: []

Empty DataFrame
Columns: [결측치, 결측률(%)]
Index: []

Empty DataFrame
Columns: [결측치, 결측률(%)]
Index: []

Empty DataFrame
Columns: [결측치, 결측률(%)]
Index: []

Empty DataFrame
Columns: [결측치, 결측률(%)]
Index: []

Empty DataFrame
Columns: [결측치, 결측률(%)]
Index: []

Empty DataFrame
Columns: [결측치, 결측률(%)]
Index: []

# 이상치 확인 및 검토

In [16]:
# 기초통계 확인
print("===== 점포-상권 =====")
display(store_clean.describe().T)

print("===== 상권변화지표-상권 =====")
display(change_clean.describe().T)

print("===== 2023년-추정매출-상권 =====")
display(sales_2023.describe().T)

print("===== 2024년-추정매출-상권 =====")
display(sales_2024.describe().T)

print("===== 2025년-추정매출-상권 =====")
display(sales_2025.describe().T)

print("===== 추정매출-상권배후지 =====")
display(sales_bg_clean.describe().T)

print("===== 길단위인구-상권 =====")
display(floating_clean.describe().T)

print("===== 상주인구-상권 =====")
display(resident_trade_clean.describe().T)

print("===== 상주인구-상권배후지 =====")
display(resident_bg_clean.describe().T)

print("===== 상주인구-서울시 =====")
display(resident_seoul_clean.describe().T)

print("===== 상주인구-자치구 =====")
display(resident_gu_clean.describe().T)

print("===== 상주인구-행정동 =====")
display(resident_dong_clean.describe().T)

print("===== 영역-상권 =====")
display(area_clean.describe().T)

===== 점포-상권 =====

,count,mean,std,min,25%,50%,75%,max
기준년분기코드,304775.0,2.025250e+04,1.117977,20251.0,20251.0,20252.0,20253.0,20254.0
상권코드,304775.0,3.114805e+06,11759.368732,3001491.0,3110437.0,3110871.0,3120138.0,3130327.0
점포수,304775.0,6.257065e+00,51.466804,0.0,1.0,2.0,5.0,11433.0
유사업종점포수,304775.0,6.790308e+00,51.863075,0.0,1.0,2.0,5.0,11444.0
개업률,304775.0,1.987030e+00,10.086123,0.0,0.0,0.0,0.0,200.0
개업점포수,304775.0,1.300730e-01,0.601829,0.0,0.0,0.0,0.0,28.0
폐업률,304775.0,2.334539e+00,11.706172,0.0,0.0,0.0,0.0,450.0
폐업점포수,304775.0,1.719268e-01,1.263042,0.0,0.0,0.0,0.0,291.0
프랜차이즈점포수,304775.0,5.332426e-01,2.389032,0.0,0.0,0.0,0.0,151.0

===== 상권변화지표-상권 =====

,count,mean,std,min,25%,50%,75%,max
기준년분기코드,36300.0,2.023514e+04,15.889882,20211.0,20222.0,20233.5,20251.0,20262.0
상권코드,36300.0,3.115222e+06,10318.672722,3001491.0,3110407.0,3110819.5,3120142.0,3130327.0
운영영업개월평균,36300.0,1.096680e+02,26.002545,3.0,94.0,106.0,121.0,351.0
폐업영업개월평균,36300.0,5.265565e+01,10.704805,20.0,47.0,51.0,56.0,226.0
서울운영영업개월평균,36300.0,1.039545e+02,7.400822,94.0,98.0,101.5,111.0,118.0
서울폐업영업개월평균,36300.0,5.136364e+01,1.431658,49.0,50.0,51.0,52.0,54.0

===== 2023년-추정매출-상권 =====

,count,mean,std,min,25%,50%,75%,max
기준년분기코드,88246.0,2.023250e+04,1.118272e+00,20231.0,20231.00,20232.0,2.023300e+04,2.023400e+04
상권코드,88246.0,3.115433e+06,1.411887e+04,3001491.0,3110527.00,3111062.0,3.120182e+06,3.130327e+06
당월매출금액,88246.0,1.044361e+09,1.000329e+10,52.0,47386848.00,176839469.0,6.259629e+08,1.373912e+12
당월매출건수,88246.0,3.560149e+04,1.672643e+05,1.0,833.00,4373.5,2.265600e+04,1.704196e+07
주중매출금액,88246.0,7.893069e+08,6.497985e+09,0.0,35141142.50,132053681.0,4.728697e+08,7.550203e+11
주말매출금액,88246.0,2.550543e+08,3.931685e+09,0.0,7244279.00,36551705.5,1.374688e+08,6.188917e+11
월요일매출금액,88246.0,1.497302e+08,1.214449e+09,0.0,5337947.00,23473457.5,8.900315e+07,1.342709e+11
화요일매출금액,88246.0,1.550976e+08,1.267584e+09,0.0,5582679.75,24190298.5,9.097706e+07,1.340662e+11
수요일매출금액,88246.0,1.557093e+08,1.257096e+09,0.0,6048438.50,25038179.0,9.208532e+07,1.382790e+11
목요일매출금액,88246.0,1.559558e+08,1.294797e+09,0.0,5874831.75,24895749.5,9.195207e+07,1.507526e+11
금요일매출금액,88246.0,1.728139e+08,1.537388e+09,0.0,6425752.00,27069725.0,1.002651e+08,1.976516e+11
토요일매출금액,88246.0,1.574051e+08,2.279607e+09,0.0,4635008.25,23163586.5,8.726682e+07,3.543533e+11
일요일매출금액,88246.0,9.764921e+07,1.681681e+09,0.0,0.00,8469329.0,4.580020e+07,2.645384e+11
시간대0006매출금액,88246.0,3.642501e+07,8.666391e+08,0.0,0.00,0.0,3.319134e+06,1.243217e+11
시간대0611매출금액,88246.0,1.161863e+08,1.352116e+09,0.0,155729.25,5960118.5,4.378234e+07,1.629674e+11
시간대1114매출금액,88246.0,2.689547e+08,2.502449e+09,0.0,5432964.50,32605690.5,1.414412e+08,2.979979e+11
시간대1417매출금액,88246.0,2.562824e+08,3.010484e+09,0.0,7554448.00,33476791.5,1.285418e+08,3.637850e+11
시간대1721매출금액,88246.0,2.814770e+08,3.065316e+09,0.0,11576768.75,47409591.0,1.723260e+08,4.805768e+11
시간대2124매출금액,88246.0,8.503584e+07,4.792352e+08,0.0,0.00,3337643.5,3.748475e+07,3.748409e+10
남성매출금액,88246.0,4.772149e+08,4.898149e+09,0.0,19044543.75,78959193.0,2.895394e+08,7.213712e+11
여성매출금액,88246.0,4.473848e+08,3.776312e+09,0.0,17560112.25,71364975.5,2.627253e+08,4.314499e+11
연령대10매출금액,88246.0,4.894689e+06,2.880126e+07,0.0,0.00,135782.5,1.983946e+06,1.616992e+09
연령대20매출금액,88246.0,1.127971e+08,8.547230e+08,0.0,1121306.25,10755844.5,5.427882e+07,1.235807e+11
연령대30매출금액,88246.0,1.863082e+08,1.774376e+09,0.0,4583427.00,24869766.0,1.026936e+08,2.442806e+11
연령대40매출금액,88246.0,2.111903e+08,1.893559e+09,0.0,7575854.75,33346974.0,1.233709e+08,2.050029e+11
연령대50매출금액,88246.0,2.069312e+08,1.966410e+09,0.0,8356410.25,34385658.5,1.237037e+08,2.238174e+11
연령대60이상매출금액,88246.0,2.024799e+08,2.469550e+09,0.0,4510303.50,22095911.0,9.411243e+07,3.553423e+11
주중매출건수,88246.0,2.680190e+04,1.127725e+05,0.0,634.00,3223.5,1.703300e+04,8.878910e+06
주말매출건수,88246.0,8.799590e+03,6.109556e+04,0.0,144.00,985.0,5.292000e+03,8.163051e+06
월요일매출건수,88246.0,5.263302e+03,2.169394e+04,0.0,110.00,604.0,3.305000e+03,1.665119e+06
화요일매출건수,88246.0,5.214865e+03,2.170936e+04,0.0,113.00,616.0,3.309000e+03,1.583966e+06
수요일매출건수,88246.0,5.316054e+03,2.201430e+04,0.0,121.00,642.0,3.377000e+03,1.567680e+06
목요일매출건수,88246.0,5.329760e+03,2.254515e+04,0.0,118.00,634.0,3.370750e+03,1.718201e+06
금요일매출건수,88246.0,5.677919e+03,2.525091e+04,0.0,130.25,706.0,3.646750e+03,2.343944e+06
토요일매출건수,88246.0,5.109878e+03,3.457913e+04,0.0,98.00,641.0,3.206000e+03,4.613556e+06
일요일매출건수,88246.0,3.689712e+03,2.689149e+04,0.0,0.00,238.5,1.908000e+03,3.549495e+06
시간대건수06매출건수,88246.0,1.227042e+03,1.085224e+04,0.0,0.00,0.0,8.700000e+01,1.246183e+06
시간대건수11매출건수,88246.0,5.142105e+03,2.871975e+04,0.0,7.00,160.0,1.783000e+03,1.819684e+06
시간대건수14매출건수,88246.0,9.501804e+03,4.672320e+04,0.0,104.00,929.0,5.778000e+03,4.169918e+06
시간대건수17매출건수,88246.0,7.583306e+03,4.575026e+04,0.0,162.00,921.0,4.550000e+03,5.167615e+06
시간대건수21매출건수,88246.0,9.239770e+03,4.623984e+04,0.0,219.00,1232.5,6.297750e+03,5.238898e+06
시간대건수24매출건수,88246.0,2.907464e+03,1.202370e+04,0.0,0.00,64.0,1.110000e+03,7.798460e+05
남성매출건수,88246.0,1.768897e+04,8.380251e+04,0.0,378.00,2136.5,1.105900e+04,9.251579e+06
여성매출건수,88246.0,1.628812e+04,7.871228e+04,0.0,326.00,1846.0,1.012375e+04,6.689606e+06
연령대10매출건수,88246.0,4.894948e+02,2.907740e+03,0.0,0.00,10.0,1.480000e+02,2.098080e+05
연령대20매출건수,88246.0,6.459008e+03,3.196557e+04,0.0,36.00,378.0,2.805000e+03,2.745723e+06
연령대30매출건수,88246.0,8.100827e+03,3.910674e+04,0.0,106.00,720.0,4.344000e+03,3.084094e+06
연령대40매출건수,88246.0,6.813440e+03,3.159513e+04,0.0,161.00,844.0,4.270000e+03,2.606367e+06
연령대50매출건수,88246.0,6.338366e+03,3.009174e+04,0.0,164.00,909.0,4.348750e+03,3.016856e+06
연령대60이상매출건수,88246.0,5.775949e+03,4.484338e+04,0.0,101.00,627.0,3.318750e+03,5.352519e+06

===== 2024년-추정매출-상권 =====

,count,mean,std,min,25%,50%,75%,max
기준년분기코드,87179.0,2.024249e+04,1.117869e+00,20241.0,20241.0,20242.0,20243.0,2.024400e+04
상권코드,87179.0,3.115444e+06,1.412624e+04,3001491.0,3110529.0,3111066.0,3120182.0,3.130327e+06
당월매출금액,87179.0,1.064983e+09,9.668534e+09,190.0,47055914.0,175016126.0,625200070.0,1.144904e+12
당월매출건수,87179.0,3.608262e+04,1.730819e+05,1.0,815.0,4286.0,22276.5,1.284697e+07
주중매출금액,87179.0,8.074585e+08,6.471138e+09,0.0,34859380.0,131067469.0,472941744.5,6.824397e+11
주말매출금액,87179.0,2.575241e+08,3.508493e+09,0.0,7079929.5,35709336.0,136450529.5,4.712509e+11
월요일매출금액,87179.0,1.574880e+08,1.231193e+09,0.0,5304675.5,23299926.0,90051640.5,1.251853e+11
화요일매출금액,87179.0,1.620910e+08,1.314549e+09,0.0,5647888.0,24404091.0,93005982.0,1.532580e+11
수요일매출금액,87179.0,1.537364e+08,1.242577e+09,0.0,5724658.5,24267063.0,89553677.5,1.354170e+11
목요일매출금액,87179.0,1.575571e+08,1.234313e+09,0.0,5781475.5,24324052.0,90933388.0,1.282475e+11
금요일매출금액,87179.0,1.765861e+08,1.536755e+09,0.0,6415728.0,26869181.0,100721891.0,2.057984e+11
토요일매출금액,87179.0,1.600429e+08,2.092999e+09,0.0,4598852.5,22739256.0,86768357.5,2.987090e+11
일요일매출금액,87179.0,9.748115e+07,1.447977e+09,0.0,0.0,8524892.0,45278279.5,1.725419e+11
시간대0006매출금액,87179.0,3.791077e+07,8.373089e+08,0.0,0.0,0.0,3505841.0,1.278766e+11
시간대0611매출금액,87179.0,1.236350e+08,1.554636e+09,0.0,216699.5,6398174.0,45590856.5,1.951202e+11
시간대1114매출금액,87179.0,2.767991e+08,2.372640e+09,0.0,5545992.0,33229376.0,142448398.0,2.567043e+11
시간대1417매출금액,87179.0,2.603322e+08,2.826931e+09,0.0,7504805.5,33026701.0,127071979.0,2.751542e+11
시간대1721매출금액,87179.0,2.824775e+08,2.865062e+09,0.0,10998618.0,45813555.0,168637301.5,4.144717e+11
시간대2124매출금액,87179.0,8.382797e+07,4.986821e+08,0.0,0.0,3021603.0,36094320.0,3.952524e+10
남성매출금액,87179.0,4.862587e+08,4.726164e+09,0.0,18753620.5,78145328.0,289660123.5,6.308875e+11
여성매출금액,87179.0,4.593941e+08,3.745730e+09,0.0,17235483.5,70236380.0,260731124.0,3.503920e+11
연령대10매출금액,87179.0,4.406868e+06,2.640161e+07,0.0,0.0,97461.0,1698263.5,1.636880e+09
연령대20매출금액,87179.0,1.044647e+08,7.874626e+08,0.0,889018.5,9365894.0,48489534.5,1.027769e+11
연령대30매출금액,87179.0,1.915816e+08,1.762306e+09,0.0,4342499.5,24345204.0,101050141.0,2.171952e+11
연령대40매출금액,87179.0,2.121948e+08,1.838329e+09,0.0,6937947.5,31828575.0,118875551.0,1.910216e+11
연령대50매출금액,87179.0,2.130366e+08,1.918153e+09,0.0,8227867.0,34350894.0,125717348.0,2.053345e+11
연령대60이상매출금액,87179.0,2.199705e+08,2.477185e+09,0.0,4962328.5,24356341.0,103491007.0,3.296473e+11
주중매출건수,87179.0,2.714076e+04,1.185462e+05,0.0,621.0,3170.0,16750.5,7.138486e+06
주말매출건수,87179.0,8.941863e+03,5.975854e+04,0.0,138.0,966.0,5210.0,5.708485e+06
월요일매출건수,87179.0,5.389976e+03,2.290733e+04,0.0,108.0,597.0,3286.0,1.384511e+06
화요일매출건수,87179.0,5.394804e+03,2.312899e+04,0.0,113.0,614.0,3335.5,1.498591e+06
수요일매출건수,87179.0,5.214532e+03,2.300911e+04,0.0,113.0,621.0,3233.0,1.426754e+06
목요일매출건수,87179.0,5.359520e+03,2.345820e+04,0.0,114.0,622.0,3306.0,1.380836e+06
금요일매출건수,87179.0,5.781928e+03,2.658783e+04,0.0,126.0,699.0,3602.0,2.241268e+06
토요일매출건수,87179.0,5.220744e+03,3.403928e+04,0.0,95.0,625.0,3158.0,3.491480e+06
일요일매출건수,87179.0,3.721120e+03,2.608503e+04,0.0,0.0,237.0,1886.0,2.217005e+06
시간대건수06매출건수,87179.0,1.206280e+03,1.088269e+04,0.0,0.0,0.0,88.0,1.312069e+06
시간대건수11매출건수,87179.0,5.293486e+03,3.045354e+04,0.0,8.0,169.0,1821.0,1.823990e+06
시간대건수14매출건수,87179.0,9.723127e+03,4.814406e+04,0.0,106.0,945.0,5811.5,3.091293e+06
시간대건수17매출건수,87179.0,7.773780e+03,4.783020e+04,0.0,161.0,910.0,4509.0,3.589262e+06
시간대건수21매출건수,87179.0,9.266060e+03,4.769386e+04,0.0,206.0,1182.0,6072.5,4.395640e+06
시간대건수24매출건수,87179.0,2.819891e+03,1.207284e+04,0.0,0.0,58.0,1051.0,6.293790e+05
남성매출건수,87179.0,1.780023e+04,8.380099e+04,0.0,366.0,2113.0,10963.0,7.228550e+06
여성매출건수,87179.0,1.664617e+04,8.600895e+04,0.0,314.0,1814.0,10030.5,6.302530e+06
연령대10매출건수,87179.0,4.397133e+02,2.821202e+03,0.0,0.0,8.0,130.0,2.154530e+05
연령대20매출건수,87179.0,5.956529e+03,3.190755e+04,0.0,29.0,327.0,2485.5,2.328871e+06
연령대30매출건수,87179.0,8.255330e+03,4.156078e+04,0.0,99.0,689.0,4309.0,2.831709e+06
연령대40매출건수,87179.0,6.819299e+03,3.294280e+04,0.0,150.0,804.0,4131.0,2.069543e+06
연령대50매출건수,87179.0,6.535319e+03,3.152190e+04,0.0,158.0,892.0,4404.5,2.484040e+06
연령대60이상매출건수,87179.0,6.440197e+03,4.826470e+04,0.0,109.0,681.0,3653.5,4.341073e+06

===== 2025년-추정매출-상권 =====

,count,mean,std,min,25%,50%,75%,max
기준년분기코드,85732.0,2.025250e+04,1.116933e+00,20251.0,20252.00,20252.0,2.025300e+04,2.025400e+04
상권코드,85732.0,3.115456e+06,1.415781e+04,3001491.0,3110534.00,3111072.5,3.120183e+06,3.130327e+06
당월매출금액,85732.0,1.080789e+09,9.191795e+09,31.0,45838107.00,172136309.0,6.159625e+08,1.148994e+12
당월매출건수,85732.0,3.560820e+04,1.732327e+05,1.0,770.00,4124.0,2.157225e+04,1.329939e+07
주중매출금액,85732.0,8.156915e+08,6.192214e+09,0.0,33776424.00,127997622.5,4.669483e+08,7.029800e+11
주말매출금액,85732.0,2.650978e+08,3.329909e+09,0.0,7125408.50,35850116.5,1.375372e+08,4.460139e+11
월요일매출금액,85732.0,1.585188e+08,1.180792e+09,0.0,5121054.75,22665597.5,8.872094e+07,1.122125e+11
화요일매출금액,85732.0,1.597231e+08,1.196965e+09,0.0,5289032.00,23322686.0,8.950829e+07,1.191794e+11
수요일매출금액,85732.0,1.599394e+08,1.236434e+09,0.0,5616288.25,23977429.5,9.116630e+07,1.445473e+11
목요일매출금액,85732.0,1.587210e+08,1.225512e+09,0.0,5624929.25,23916224.0,8.967224e+07,1.452027e+11
금요일매출금액,85732.0,1.787891e+08,1.435676e+09,0.0,6163400.75,26408262.0,9.993116e+07,1.818381e+11
토요일매출금액,85732.0,1.643153e+08,1.935650e+09,0.0,4552780.75,22728233.0,8.740899e+07,2.684213e+11
일요일매출금액,85732.0,1.007825e+08,1.428440e+09,0.0,0.00,8722062.0,4.583815e+07,1.775926e+11
시간대0006매출금액,85732.0,3.799190e+07,8.607884e+08,0.0,0.00,0.0,3.254136e+06,1.266549e+11
시간대0611매출금액,85732.0,1.293082e+08,1.446269e+09,0.0,219775.50,6667712.0,4.659506e+07,1.643040e+11
시간대1114매출금액,85732.0,2.825852e+08,2.257160e+09,0.0,5528060.25,33477431.0,1.441812e+08,2.271113e+11
시간대1417매출금액,85732.0,2.655601e+08,2.744876e+09,0.0,7401949.50,32608535.0,1.272428e+08,2.759481e+11
시간대1721매출금액,85732.0,2.829528e+08,2.705338e+09,0.0,10504726.50,44658789.5,1.656352e+08,4.102962e+11
시간대2124매출금액,85732.0,8.239107e+07,5.168120e+08,0.0,0.00,2712248.0,3.452531e+07,4.199821e+10
남성매출금액,85732.0,4.899551e+08,4.396794e+09,0.0,18280310.25,76770266.5,2.863432e+08,5.936228e+11
여성매출금액,85732.0,4.681600e+08,3.728371e+09,0.0,16907146.00,69141832.5,2.598762e+08,3.687561e+11
연령대10매출금액,85732.0,4.275442e+06,2.610628e+07,0.0,0.00,73672.0,1.554914e+06,1.385634e+09
연령대20매출금액,85732.0,9.672955e+07,7.249668e+08,0.0,738891.00,8342505.5,4.402626e+07,1.018944e+11
연령대30매출금액,85732.0,1.878695e+08,1.617797e+09,0.0,3982116.00,23108759.5,9.813289e+07,2.055992e+11
연령대40매출금액,85732.0,2.122886e+08,1.723246e+09,0.0,6371059.25,30461045.5,1.165229e+08,1.638682e+11
연령대50매출금액,85732.0,2.149905e+08,1.904994e+09,0.0,7871619.75,33543904.5,1.240934e+08,1.918168e+11
연령대60이상매출금액,85732.0,2.419627e+08,2.510243e+09,0.0,5389267.25,26276566.5,1.119474e+08,2.980817e+11
주중매출건수,85732.0,2.663086e+04,1.175179e+05,0.0,585.00,3046.0,1.618925e+04,7.468026e+06
주말매출건수,85732.0,8.977341e+03,6.078342e+04,0.0,132.00,933.0,5.090500e+03,5.831362e+06
월요일매출건수,85732.0,5.249032e+03,2.252447e+04,0.0,102.00,567.0,3.165000e+03,1.140818e+06
화요일매출건수,85732.0,5.176356e+03,2.265854e+04,0.0,103.00,576.0,3.136000e+03,1.191447e+06
수요일매출건수,85732.0,5.261076e+03,2.317981e+04,0.0,109.00,602.0,3.201000e+03,1.637572e+06
목요일매출건수,85732.0,5.282964e+03,2.356315e+04,0.0,109.00,599.0,3.192250e+03,1.510741e+06
금요일매출건수,85732.0,5.661433e+03,2.610529e+04,0.0,119.00,670.0,3.456000e+03,2.036222e+06
토요일매출건수,85732.0,5.223276e+03,3.427878e+04,0.0,91.00,603.0,3.084000e+03,3.442309e+06
일요일매출건수,85732.0,3.754066e+03,2.686122e+04,0.0,0.00,233.0,1.845000e+03,2.389053e+06
시간대건수06매출건수,85732.0,1.159285e+03,1.015782e+04,0.0,0.00,0.0,8.100000e+01,1.148437e+06
시간대건수11매출건수,85732.0,5.249373e+03,3.064082e+04,0.0,8.00,171.0,1.811000e+03,1.676457e+06
시간대건수14매출건수,85732.0,9.743859e+03,5.015622e+04,0.0,104.00,920.0,5.723000e+03,3.065320e+06
시간대건수17매출건수,85732.0,7.804662e+03,5.158059e+04,0.0,155.00,880.0,4.417000e+03,4.054339e+06
시간대건수21매출건수,85732.0,8.973499e+03,4.442740e+04,0.0,192.00,1107.5,5.739250e+03,4.399314e+06
시간대건수24매출건수,85732.0,2.677525e+03,1.141530e+04,0.0,0.00,50.0,9.582500e+02,5.208220e+05
남성매출건수,85732.0,1.748732e+04,8.368368e+04,0.0,345.00,2015.0,1.050700e+04,7.231893e+06
여성매출건수,85732.0,1.649272e+04,8.606268e+04,0.0,301.00,1749.5,9.816250e+03,5.110243e+06
연령대10매출건수,85732.0,3.958139e+02,2.431120e+03,0.0,0.00,7.0,1.140000e+02,1.796800e+05
연령대20매출건수,85732.0,5.330241e+03,2.732389e+04,0.0,24.00,285.0,2.189250e+03,1.599813e+06
연령대30매출건수,85732.0,7.935116e+03,3.816054e+04,0.0,89.00,649.0,4.038000e+03,2.592933e+06
연령대40매출건수,85732.0,6.611026e+03,3.159775e+04,0.0,134.00,751.0,3.884000e+03,1.979297e+06
연령대50매출건수,85732.0,6.549409e+03,3.340550e+04,0.0,148.00,852.0,4.286000e+03,2.381030e+06
연령대60이상매출건수,85732.0,7.158441e+03,5.913484e+04,0.0,112.00,723.0,3.927250e+03,4.965867e+06

===== 추정매출-상권배후지 =====

,count,mean,std,min,25%,50%,75%,max
기준년분기코드,147035.0,2.025250e+04,1.117314e+00,20251.0,20251.0,20252.0,20253.0,2.025400e+04
상권코드,147035.0,3.110555e+06,3.101068e+02,3110001.0,3110281.0,3110561.0,3110823.0,3.111090e+06
당월매출금액,147035.0,8.744127e+08,3.359619e+09,226.0,52495868.0,200805906.0,691157192.5,2.806183e+11
당월매출건수,147035.0,3.453526e+04,1.093096e+05,1.0,776.0,4186.0,22649.0,1.213673e+07
주중매출금액,147035.0,6.677882e+08,2.607618e+09,0.0,39550690.0,151001697.0,524939259.5,1.974541e+11
주말매출금액,147035.0,2.066244e+08,8.504672e+08,0.0,7532522.5,40344389.0,156034854.0,8.485356e+10
월요일매출금액,147035.0,1.323048e+08,5.309794e+08,0.0,6048959.5,27405385.0,100504284.0,3.651338e+10
화요일매출금액,147035.0,1.307106e+08,5.337251e+08,0.0,6162096.0,27613357.0,101112911.0,4.022707e+10
수요일매출금액,147035.0,1.308995e+08,5.350256e+08,0.0,6415094.0,28203423.0,101889132.0,4.300159e+10
목요일매출금액,147035.0,1.284127e+08,5.130184e+08,0.0,6305601.0,27953039.0,100039699.5,4.611487e+10
금요일매출금액,147035.0,1.454607e+08,5.804185e+08,0.0,6776737.0,30783789.0,111623679.0,4.168915e+10
토요일매출금액,147035.0,1.294033e+08,5.148848e+08,0.0,4914427.0,26268658.0,100460835.5,5.211350e+10
일요일매출금액,147035.0,7.722112e+07,3.495472e+08,0.0,0.0,8705094.0,49284741.0,3.522756e+10
시간대00~06매출금액,147035.0,2.780004e+07,1.668070e+08,0.0,0.0,0.0,2587859.0,1.776404e+10
시간대06~11매출금액,147035.0,1.111500e+08,7.730638e+08,0.0,529625.0,9590308.0,63478853.0,7.603059e+10
시간대11~14매출금액,147035.0,2.217910e+08,1.036216e+09,0.0,6195728.5,38302391.0,159954919.5,9.805352e+10
시간대14~17매출금액,147035.0,2.092665e+08,1.033764e+09,0.0,9194585.0,40698843.0,160619696.5,9.775088e+10
시간대17~21매출금액,147035.0,2.332306e+08,7.172946e+08,0.0,11856288.0,52665054.0,178534995.0,4.986249e+10
시간대21~24매출금액,147035.0,7.117452e+07,2.804160e+08,0.0,0.0,2313762.0,29791174.0,1.563545e+10
남성매출금액,147035.0,4.183382e+08,1.604538e+09,0.0,20830566.5,89412141.0,320965264.0,1.201562e+11
여성매출금액,147035.0,3.851588e+08,1.587873e+09,0.0,18282198.0,80394709.0,302507763.0,1.520222e+11
연령대10매출금액,147035.0,3.380291e+06,1.441472e+07,0.0,0.0,44818.0,1812381.5,9.548834e+08
연령대20매출금액,147035.0,7.139787e+07,2.580528e+08,0.0,658389.5,8538121.0,44932490.5,1.231870e+10
연령대30매출금액,147035.0,1.400221e+08,4.536471e+08,0.0,4035505.0,24996405.0,103004359.0,2.305195e+10
연령대40매출금액,147035.0,1.698790e+08,7.211319e+08,0.0,6666462.5,34965147.0,130800512.5,7.914422e+10
연령대50매출금액,147035.0,1.893766e+08,7.982953e+08,0.0,8954890.5,40488899.0,148181823.0,6.001640e+10
연령대60이상매출금액,147035.0,2.294426e+08,1.438531e+09,0.0,6835371.0,34154558.0,139870890.0,1.707403e+11
주중매출건수,147035.0,2.575129e+04,7.736855e+04,0.0,600.0,3127.0,16843.5,7.995098e+06
주말매출건수,147035.0,8.783976e+03,3.360298e+04,0.0,126.0,932.0,5578.0,4.161697e+06
월요일매출건수,147035.0,5.192373e+03,1.549471e+04,0.0,109.0,597.0,3253.5,1.483634e+06
화요일매출건수,147035.0,5.012569e+03,1.511654e+04,0.0,108.0,593.0,3278.0,1.613297e+06
수요일매출건수,147035.0,5.050041e+03,1.508731e+04,0.0,112.0,618.0,3336.0,1.748017e+06
목요일매출건수,147035.0,5.055084e+03,1.546761e+04,0.0,111.0,609.0,3326.0,1.686082e+06
금요일매출건수,147035.0,5.441221e+03,1.653056e+04,0.0,118.0,674.0,3635.0,1.798095e+06
토요일매출건수,147035.0,5.138569e+03,1.912948e+04,0.0,88.0,624.0,3450.0,2.442777e+06
일요일매출건수,147035.0,3.645407e+03,1.476412e+04,0.0,0.0,209.0,1891.0,1.877200e+06
시간대00~06매출건수,147035.0,1.255081e+03,6.059749e+03,0.0,0.0,0.0,71.0,2.761370e+05
시간대06~11매출건수,147035.0,5.050925e+03,2.022384e+04,0.0,14.0,211.0,2151.0,2.227916e+06
시간대11~14매출건수,147035.0,8.542400e+03,3.214716e+04,0.0,110.0,843.0,5801.0,4.300879e+06
시간대14~17매출건수,147035.0,7.533612e+03,3.197781e+04,0.0,178.0,941.0,5131.0,4.770585e+06
시간대17~21매출건수,147035.0,9.194906e+03,2.462760e+04,0.0,194.0,1135.0,6167.5,1.528414e+06
시간대21~24매출건수,147035.0,2.958340e+03,1.046794e+04,0.0,0.0,38.0,879.0,2.683100e+05
남성매출건수,147035.0,1.771551e+04,5.453745e+04,0.0,342.0,2074.0,10891.5,5.323380e+06
여성매출건수,147035.0,1.585190e+04,5.469678e+04,0.0,297.0,1723.0,10593.5,6.760072e+06
연령대10매출건수,147035.0,3.893358e+02,2.138530e+03,0.0,0.0,5.0,129.0,2.549350e+05
연령대20매출건수,147035.0,4.719473e+03,1.661796e+04,0.0,21.0,240.0,2135.0,6.191040e+05
연령대30매출건수,147035.0,7.044197e+03,2.059736e+04,0.0,84.0,577.0,3889.5,7.360630e+05
연령대40매출건수,147035.0,6.233305e+03,1.795939e+04,0.0,130.0,749.0,3972.0,1.411521e+06
연령대50매출건수,147035.0,6.977529e+03,2.183177e+04,0.0,147.0,910.0,4632.5,2.391432e+06
연령대60이상매출건수,147035.0,8.203590e+03,4.762084e+04,0.0,122.0,855.0,4710.0,7.535945e+06

===== 길단위인구-상권 =====

,count,mean,std,min,25%,50%,75%,max
기준년분기코드,36281.0,2.023513e+04,15.890410,20211.0,20222.0,20233.0,20251.0,20262.0
상권코드,36281.0,3.115224e+06,10320.912824,3001491.0,3110407.0,3110819.0,3120142.0,3130327.0
총유동인구수,36281.0,8.211617e+05,885382.886778,4.0,221149.0,557111.0,1132383.0,8816195.0
남성유동인구수,36281.0,3.905698e+05,428550.438138,0.0,106269.0,263883.0,534272.0,4797974.0
여성유동인구수,36281.0,4.305919e+05,460210.340471,0.0,115278.0,292661.0,593377.0,4144646.0
연령대10유동인구수,36281.0,1.045798e+05,112464.565369,0.0,25402.0,69748.0,145205.0,1136870.0
연령대20유동인구수,36281.0,1.454480e+05,207963.340820,0.0,31480.0,81444.0,181583.0,3487417.0
연령대30유동인구수,36281.0,1.453224e+05,179326.247045,0.0,35918.0,92274.0,186707.0,2077519.0
연령대40유동인구수,36281.0,1.335061e+05,151433.698612,0.0,36433.0,89576.0,179235.0,1704350.0
연령대50유동인구수,36281.0,1.203061e+05,127593.482093,0.0,33287.0,82703.0,167446.0,1605899.0
연령대60이상유동인구수,36281.0,1.719992e+05,179711.810184,0.0,46051.0,118313.0,240410.0,2116044.0
시간대0006유동인구수,36281.0,1.965366e+05,209377.106178,0.0,48214.0,129573.0,276017.0,2066410.0
시간대0611유동인구수,36281.0,1.673834e+05,177381.746124,0.0,45729.0,115226.0,232422.0,1714738.0
시간대1114유동인구수,36281.0,1.062318e+05,131546.304118,0.0,28245.0,70845.0,139640.0,1871525.0
시간대1417유동인구수,36281.0,1.073132e+05,134570.751032,0.0,28570.0,70907.0,139923.0,1877577.0
시간대1721유동인구수,36281.0,1.424058e+05,164375.601565,0.0,38433.0,94557.0,192355.0,1793125.0
시간대2124유동인구수,36281.0,1.012909e+05,107514.022501,0.0,26026.0,68188.0,139862.0,932288.0
월요일유동인구수,36281.0,1.176617e+05,127737.382066,0.0,31584.0,79980.0,162697.0,1344871.0
화요일유동인구수,36281.0,1.183071e+05,129603.322356,0.0,31696.0,80199.0,163233.0,1412294.0
수요일유동인구수,36281.0,1.186374e+05,130199.574509,0.0,31788.0,80384.0,163460.0,1410371.0
목요일유동인구수,36281.0,1.186758e+05,130534.150024,0.0,31858.0,80253.0,163395.0,1401446.0
금요일유동인구수,36281.0,1.185492e+05,130781.404716,0.0,31846.0,80142.0,162867.0,1424450.0
토요일유동인구수,36281.0,1.155433e+05,123656.331800,0.0,30903.0,78571.0,159135.0,1123902.0
일요일유동인구수,36281.0,1.137872e+05,119055.970688,0.0,30221.0,77555.0,157122.0,1072841.0

===== 상주인구-상권 =====

,count,mean,std,min,25%,50%,75%,max
기준년분기코드,35908.0,2.023514e+04,15.895140,20211.0,20222.0,20234.0,20251.0,20262.0
상권코드,35908.0,3.115109e+06,10296.190618,3001491.0,3110403.0,3110811.0,3120133.0,3130327.0
총상주인구수,35908.0,2.320338e+03,2278.249882,1.0,640.0,1614.0,3269.0,21341.0
남성상주인구수,35908.0,1.137058e+03,1116.841234,0.0,318.0,800.0,1606.0,10459.0
여성상주인구수,35908.0,1.183279e+03,1169.368618,0.0,322.0,821.0,1681.0,10882.0
연령대10상주인구수,35908.0,2.238017e+02,253.398835,0.0,51.0,144.0,311.0,3078.0
연령대20상주인구수,35908.0,3.894481e+02,452.789695,0.0,89.0,251.0,530.0,5174.0
연령대30상주인구수,35908.0,4.005712e+02,442.757272,0.0,96.0,265.0,557.0,4207.0
연령대40상주인구수,35908.0,3.346957e+02,348.445280,0.0,86.0,226.0,467.0,4280.0
연령대50상주인구수,35908.0,3.598389e+02,360.259293,0.0,94.0,248.0,514.0,3161.0
연령대60이상상주인구수,35908.0,6.119819e+02,610.058885,0.0,165.0,427.0,860.0,5181.0
남성연령대10상주인구수,35908.0,1.146017e+02,130.199678,0.0,26.0,74.0,159.0,1586.0
남성연령대20상주인구수,35908.0,1.827971e+02,208.606478,0.0,43.0,120.0,252.0,2212.0
남성연령대30상주인구수,35908.0,2.064392e+02,228.009840,0.0,50.0,138.0,286.0,2148.0
남성연령대40상주인구수,35908.0,1.721655e+02,178.405610,0.0,46.0,117.0,237.0,2235.0
남성연령대50상주인구수,35908.0,1.807821e+02,178.735433,0.0,49.0,126.0,257.0,1577.0
남성연령대60이상상주인구수,35908.0,2.802729e+02,278.313154,0.0,77.0,195.0,392.0,2260.0
여성연령대10상주인구수,35908.0,1.092000e+02,123.880857,0.0,25.0,70.0,152.0,1492.0
여성연령대20상주인구수,35908.0,2.066510e+02,252.977032,0.0,44.0,129.0,274.0,3153.0
여성연령대30상주인구수,35908.0,1.941321e+02,219.313169,0.0,46.0,125.0,265.0,2070.0
여성연령대40상주인구수,35908.0,1.625302e+02,172.357305,0.0,40.0,107.0,228.0,2045.0
여성연령대50상주인구수,35908.0,1.790568e+02,183.699656,0.0,45.0,120.0,256.0,1584.0
여성연령대60이상상주인구수,35908.0,3.317090e+02,333.711272,0.0,87.0,230.0,469.0,2921.0
총가구수,35908.0,1.284343e+03,1266.849434,1.0,365.0,912.0,1821.0,9357.0
아파트가구수,35908.0,0.000000e+00,0.000000,0.0,0.0,0.0,0.0,0.0
비아파트가구수,35908.0,1.284343e+03,1266.849434,1.0,365.0,912.0,1821.0,9357.0

===== 상주인구-상권배후지 =====

,count,mean,std,min,25%,50%,75%,max
기준년분기코드,23980.0,2.023514e+04,15.889995,20211.0,20222.00,20233.5,20251.00,20262.0
상권배후지코드,23980.0,3.110546e+06,314.662325,3110001.0,3110273.00,3110545.5,3110818.00,3111090.0
총상주인구수,23980.0,1.306384e+04,6796.402829,1.0,8141.00,12146.0,17346.00,47137.0
남성상주인구수,23980.0,6.375760e+03,3328.096414,1.0,3963.00,5906.0,8461.25,22937.0
여성상주인구수,23980.0,6.688083e+03,3486.460406,0.0,4182.00,6173.0,8901.00,24200.0
연령대10상주인구수,23980.0,1.515531e+03,894.011008,0.0,850.00,1363.0,2036.00,6280.0
연령대20상주인구수,23980.0,1.958887e+03,1230.935181,0.0,1104.00,1701.5,2557.00,9709.0
연령대30상주인구수,23980.0,2.074839e+03,1198.584258,0.0,1225.00,1857.0,2717.00,8664.0
연령대40상주인구수,23980.0,1.940142e+03,1055.887592,0.0,1178.00,1773.0,2544.00,9000.0
연령대50상주인구수,23980.0,2.084610e+03,1124.214272,0.0,1264.00,1910.0,2773.00,6917.0
연령대60이상상주인구수,23980.0,3.489835e+03,1939.854436,0.0,2021.75,3158.0,4716.00,12156.0
남성연령대10상주인구수,23980.0,7.757937e+02,459.217736,0.0,437.00,699.0,1042.00,3295.0
남성연령대20상주인구수,23980.0,9.414644e+02,579.381780,0.0,538.00,825.0,1234.00,4257.0
남성연령대30상주인구수,23980.0,1.056698e+03,621.707958,0.0,619.00,945.0,1377.00,4577.0
남성연령대40상주인구수,23980.0,9.838456e+02,537.667020,0.0,598.00,904.0,1294.00,4663.0
남성연령대50상주인구수,23980.0,1.029064e+03,550.947088,0.0,635.00,953.0,1367.00,3244.0
남성연령대60이상상주인구수,23980.0,1.588895e+03,883.126852,0.0,923.00,1443.0,2131.00,5595.0
여성연령대10상주인구수,23980.0,7.397373e+02,437.041194,0.0,416.00,663.0,997.00,2998.0
여성연령대20상주인구수,23980.0,1.017423e+03,668.544942,0.0,557.00,866.0,1315.00,5517.0
여성연령대30상주인구수,23980.0,1.018141e+03,589.429596,0.0,599.75,912.0,1331.00,4144.0
여성연령대40상주인구수,23980.0,9.562967e+02,525.399849,0.0,573.00,871.0,1262.00,4337.0
여성연령대50상주인구수,23980.0,1.055546e+03,578.094447,0.0,627.00,960.0,1405.00,3731.0
여성연령대60이상상주인구수,23980.0,1.900940e+03,1061.236512,0.0,1096.00,1723.0,2579.00,6612.0
총가구수,23980.0,6.518889e+03,3469.836973,1.0,3986.75,5972.5,8663.25,22628.0
아파트가구수,23980.0,0.000000e+00,0.000000,0.0,0.00,0.0,0.00,0.0
비아파트가구수,23980.0,6.518889e+03,3469.836973,1.0,3986.75,5972.5,8663.25,22628.0

===== 상주인구-서울시 =====

,count,mean,std,min,25%,50%,75%,max
기준년분기코드,22.0,2.023514e+04,16.263589,20211.0,20222.25,20233.5,20249.25,20262.0
서울시코드,22.0,1.100000e+01,0.000000,11.0,11.00,11.0,11.00,11.0
총상주인구수,22.0,9.466263e+06,139747.315420,9360421.0,9360421.00,9385582.5,9664310.00,9664310.0
남성상주인구수,22.0,4.599308e+06,78262.560599,4527676.0,4527676.00,4574288.0,4699535.00,4699535.0
여성상주인구수,22.0,4.866954e+06,70250.998019,4789844.0,4832745.00,4832745.0,4964775.00,4964775.0
연령대10상주인구수,22.0,1.282299e+06,89874.735728,1173338.0,1243704.00,1243704.0,1405211.00,1405211.0
연령대20상주인구수,22.0,1.335072e+06,134532.612708,1075764.0,1350090.00,1350090.0,1459649.00,1459649.0
연령대30상주인구수,22.0,1.440235e+06,24525.932792,1421660.0,1421660.00,1426075.5,1474993.00,1474993.0
연령대40상주인구수,22.0,1.473640e+06,58642.622620,1416424.0,1416424.00,1472034.5,1527645.00,1536473.0
연령대50상주인구수,22.0,1.509443e+06,17830.199800,1492389.0,1492389.00,1507543.0,1522697.00,1533146.0
연령대60이상상주인구수,22.0,2.425574e+06,135315.295342,2274115.0,2274115.00,2436154.0,2436154.00,2661532.0
남성연령대10상주인구수,22.0,6.577439e+05,46309.886809,602775.0,637249.00,637249.0,721361.00,721361.0
남성연령대20상주인구수,22.0,6.455580e+05,55087.896862,549785.0,641002.00,641002.0,707445.00,707445.0
남성연령대30상주인구수,22.0,7.193590e+05,12932.763930,709883.0,711041.00,711041.0,737845.00,737845.0
남성연령대40상주인구수,22.0,7.309848e+05,30844.891692,701112.0,701112.00,728861.5,756611.00,768289.0
남성연령대50상주인구수,22.0,7.427843e+05,10915.504353,733018.0,733018.00,740494.5,747971.00,760565.0
남성연령대60이상상주인구수,22.0,1.102878e+06,70098.158412,1028302.0,1028302.00,1104254.0,1104254.00,1229603.0
여성연령대10상주인구수,22.0,6.245549e+05,43575.623062,570563.0,606455.00,606455.0,683850.00,683850.0
여성연령대20상주인구수,22.0,6.895142e+05,81269.567266,525979.0,709088.00,709088.0,752204.00,752204.0
여성연령대30상주인구수,22.0,7.208762e+05,11974.178015,710619.0,710619.00,715613.5,737148.00,737148.0
여성연령대40상주인구수,22.0,7.426548e+05,28003.850917,715312.0,715312.00,741748.0,771034.00,771034.0
여성연령대50상주인구수,22.0,7.666585e+05,7496.285231,759371.0,759371.00,765976.0,774726.00,774726.0
여성연령대60이상상주인구수,22.0,1.322696e+06,65478.536197,1245813.0,1245813.00,1331900.0,1331900.00,1431929.0
총가구수,22.0,4.433594e+06,20698.388639,4413371.0,4413371.00,4433593.5,4453816.00,4453816.0
아파트가구수,22.0,0.000000e+00,0.000000,0.0,0.00,0.0,0.00,0.0
비아파트가구수,22.0,4.433594e+06,20698.388639,4413371.0,4413371.00,4433593.5,4453816.00,4453816.0

===== 상주인구-자치구 =====

,count,mean,std,min,25%,50%,75%,max
기준년분기코드,550.0,20235.136364,15.904128,20211.0,20222.00,20233.5,20251.0,20262.0
자치구코드,550.0,11416.600000,186.511899,11110.0,11260.00,11410.0,11560.0,11740.0
총상주인구수,550.0,378650.503636,124850.888361,120961.0,306437.00,380369.5,459485.0,667802.0
남성상주인구수,550.0,183972.329091,60215.325500,58499.0,148571.00,187074.0,223326.0,322197.0
여성상주인구수,550.0,194678.174545,64795.239632,60915.0,157952.00,195194.0,233511.0,345605.0
연령대10상주인구수,550.0,51291.950909,22351.293031,11764.0,37747.00,46999.0,69313.0,109764.0
연령대20상주인구수,550.0,53402.889091,19663.224833,11504.0,40333.00,55217.5,64315.5,109023.0
연령대30상주인구수,550.0,57609.409091,20650.882500,18814.0,44858.00,57820.0,66290.0,110605.0
연령대40상주인구수,550.0,58945.583636,22008.381399,16721.0,45014.00,57853.0,72463.0,109290.0
연령대50상주인구수,550.0,60377.712727,19354.033503,19024.0,50233.00,57350.5,72151.0,103598.0
연령대60이상상주인구수,550.0,97022.958182,29365.024535,34052.0,80218.25,98360.0,116762.0,164620.0
남성연령대10상주인구수,550.0,26309.756364,11592.253472,5962.0,19484.00,23706.0,36206.5,56407.0
남성연령대20상주인구수,550.0,25822.321818,9424.512355,5815.0,19734.00,26087.5,30645.0,53111.0
남성연령대30상주인구수,550.0,28774.360000,10229.572700,9540.0,22027.00,29033.0,32468.0,55501.0
남성연령대40상주인구수,550.0,29239.390909,10453.695164,8518.0,22572.00,29553.0,35976.0,52629.0
남성연령대50상주인구수,550.0,29711.372727,9338.918902,9501.0,24836.00,28137.5,35131.0,50695.0
남성연령대60이상상주인구수,550.0,44115.127273,13334.772634,15610.0,35310.50,44603.0,53319.0,77341.0
여성연령대10상주인구수,550.0,24982.194545,10763.733489,5802.0,18263.00,22576.0,33309.5,53357.0
여성연령대20상주인구수,550.0,27580.567273,10352.894858,5689.0,19935.75,28250.0,32960.0,55912.0
여성연령대30상주인구수,550.0,28835.049091,10617.560445,9274.0,22649.00,29351.0,33996.0,57546.0
여성연령대40상주인구수,550.0,29706.192727,11672.413947,8203.0,22442.00,28491.0,37707.0,56661.0
여성연령대50상주인구수,550.0,30666.340000,10042.598557,9366.0,25397.00,29859.0,37020.0,52903.0
여성연령대60이상상주인구수,550.0,52907.830909,16097.726050,18442.0,44085.00,53437.0,63405.0,87703.0
총가구수,550.0,177343.740000,54939.891074,63375.0,143436.00,180457.0,202602.0,285415.0
아파트가구수,550.0,0.000000,0.000000,0.0,0.00,0.0,0.0,0.0
비아파트가구수,550.0,177343.740000,54939.891074,63375.0,143436.00,180457.0,202602.0,285415.0

===== 상주인구-행정동 =====

,count,mean,std,min,25%,50%,75%,max
기준년분기코드,9350.0,2.023514e+04,15.890513,20211.0,20222.00,20233.5,20251.00,20262.0
행정동코드,9350.0,1.143342e+07,191510.835659,11110515.0,11260655.00,11440630.0,11590680.00,11740700.0
총상주인구수,9350.0,2.227356e+04,9130.625913,16.0,16335.00,21666.0,27483.50,57020.0
남성상주인구수,9350.0,1.082190e+04,4407.626768,10.0,7869.00,10528.0,13389.00,26773.0
여성상주인구수,9350.0,1.145166e+04,4751.260172,6.0,8473.00,11082.0,14213.00,30247.0
연령대10상주인구수,9350.0,3.017174e+03,1877.700216,2.0,1735.00,2617.0,3848.00,12586.0
연령대20상주인구수,9350.0,3.141346e+03,1598.232192,0.0,2079.00,2909.0,4008.00,11517.0
연령대30상주인구수,9350.0,3.388789e+03,1601.595049,1.0,2304.00,3217.0,4330.75,10320.0
연령대40상주인구수,9350.0,3.467387e+03,1664.312573,0.0,2395.00,3252.0,4351.75,10773.0
연령대50상주인구수,9350.0,3.551630e+03,1486.455531,1.0,2559.00,3419.0,4479.00,9883.0
연령대60이상상주인구수,9350.0,5.707233e+03,2342.678095,7.0,4155.00,5490.0,7110.00,14661.0
남성연령대10상주인구수,9350.0,1.547633e+03,967.482251,2.0,899.50,1352.0,1947.00,6484.0
남성연령대20상주인구수,9350.0,1.518960e+03,743.990324,0.0,1028.00,1420.0,1908.00,5321.0
남성연령대30상주인구수,9350.0,1.692609e+03,804.592246,1.0,1137.00,1588.0,2158.00,5501.0
남성연령대40상주인구수,9350.0,1.719964e+03,796.908384,0.0,1220.00,1628.0,2137.00,5146.0
남성연령대50상주인구수,9350.0,1.747728e+03,726.034599,0.0,1255.00,1682.0,2202.00,4916.0
남성연령대60이상상주인구수,9350.0,2.595007e+03,1058.959793,5.0,1867.00,2480.0,3212.75,6767.0
여성연령대10상주인구수,9350.0,1.469541e+03,914.471047,0.0,849.00,1268.0,1869.00,6102.0
여성연령대20상주인구수,9350.0,1.622386e+03,880.772911,0.0,1037.00,1478.0,2082.50,6391.0
여성연령대30상주인구수,9350.0,1.696179e+03,819.282156,0.0,1147.00,1584.0,2160.50,5490.0
여성연령대40상주인구수,9350.0,1.747423e+03,882.227064,0.0,1149.25,1614.0,2205.00,5755.0
여성연령대50상주인구수,9350.0,1.803902e+03,769.149672,1.0,1294.25,1741.0,2281.00,4967.0
여성연령대60이상상주인구수,9350.0,3.112225e+03,1294.764388,2.0,2251.00,3001.0,3899.00,7894.0
총가구수,9350.0,1.043198e+04,4234.976121,11.0,7552.00,10083.5,12872.00,28118.0
아파트가구수,9350.0,0.000000e+00,0.000000,0.0,0.00,0.0,0.00,0.0
비아파트가구수,9350.0,1.043198e+04,4234.976121,11.0,7552.00,10083.5,12872.00,28118.0

===== 영역-상권 =====

,count,mean,std,min,25%,50%,75%,max
상권코드,1650.0,3.115222e+06,10321.658840,3001491.0,3110407.25,3110819.5,3120141.75,3130327.0
엑스좌표값,1650.0,1.989818e+05,7280.720618,182509.0,192815.25,200096.0,204366.25,215352.0
와이좌표값,1650.0,4.498755e+05,5590.503325,437249.0,445178.50,449849.5,453563.50,465573.0
자치구코드,1650.0,1.142622e+04,190.533628,11110.0,11260.00,11440.0,11590.00,11740.0
행정동코드,1650.0,1.142686e+07,190548.800843,11110515.0,11260575.00,11440590.0,11590560.00,11740700.0
영역면적,1650.0,9.992795e+04,118818.942812,1854.0,35330.00,71927.5,128147.25,2462734.0

In [17]:
# 식별자를 제외하도록 함수 수정
def check_outlier(df):
    # 수치형 컬럼 선택
    numeric_cols = df.select_dtypes(include='number').columns # df에서 숫자형(int, float 등) 데이터 타입을 가진 컬럼만 선택

    # 이상치 분석에서 제외할 식별자 컬럼 지정 -> exclude_cols =[제외할 컬럼 지정]
    # 연도/분기, 상권, 지역 등을 구분하기 위한 "코드(식별번호)"이므로 제외
    exclude_cols = [
        '기준년분기코드',
        '상권코드',
        '상권배후지코드',
        '서울시코드',
        '자치구코드',
        '행정동코드'
    ]

    # 실제로 분석할 숫자형 컬럼만 남기기 = 숫자형 컬럼 중에서 식별자 컬럼 제외 작업
    numeric_cols = [
        col for col in numeric_cols # numeric_cols에 있는 컬럼을 하나씩 col에 넣어서 확인.
        if col not in exclude_cols # 현재 컬럼이 exclude_cols(제외할 식별자 컬럼 명단) 안에 없다면 남김.
    ]

    # 결과를 저장할 빈 리스트 생성 -> result
    result = []

    for col in numeric_cols: # 컬럼을 하나씩 검사
        Q1 = df[col].quantile(0.25) # 현재 검사중인 컬럼을 가져옴 -> 해당 데이터의 25% 지점 값을 구함.   # 1사분위수(Q1)
        Q3 = df[col].quantile(0.75) # 현재 검사중인 컬럼을 가져옴 -> 해당 데이터의 75% 지점 값을 구함.   # 3사분위수(Q3)
        IQR = Q3 - Q1 # IQR = 3사분위수 - 1사분위수  # IQR = 통계 용어 "InterQuartile Range(사분위 범위)"의 약자.

        lower = Q1 - 1.5 * IQR # 이상치 하한값 계산
        upper = Q3 + 1.5 * IQR # 이상치 상한값 계산
        # 여기서 1.5는 데이터에서 일반적인 변동 범위를 적절하게 잡기 위한 실용적인 기준.
        
        
        outlier_count = (
            (df[col] < lower) |  # 하한값을 실제 데이터와 비교하여 너무 작은 값 찾기.
            (df[col] > upper)   #  상한값을 실제 데이터와 비교하여 너무 큰 값 찾기.
        ).sum() # 이상치 후보는 총 몇개인가?

        result.append([
            col, # 현재 검사 중인 컬럼(col)을 append하여 리스트 맨 뒤에 검사해서 또 추가함.
            outlier_count,
            lower,
            upper
        ])

    return pd.DataFrame(
        result,
        columns=['컬럼명', '이상치후보수', '하한값', '상한값']
    )

In [18]:
print("=== 점포-상권 ===")
display(check_outlier(store_clean))
print("\n=== 상권변화지표-상권 ===")
display(check_outlier(change_clean))
print("\n=== 2023년-추정매출-상권 ===")
display(check_outlier(sales_2023))
print("\n=== 2024년-추정매출-상권 ===")
display(check_outlier(sales_2024))
print("\n=== 2025년-추정매출-상권 ===")
display(check_outlier(sales_2025))
print("\n=== 추정매출-상권배후지 ===")
display(check_outlier(sales_bg_clean))
print("\n=== 길단위인구-상권 ===")
display(check_outlier(floating_clean))
print("\n=== 상주인구-상권 ===")
display(check_outlier(resident_trade_clean))
print("\n=== 상주인구-상권배후지 ===")
display(check_outlier(resident_bg_clean))
print("\n=== 상주인구-서울시 ===")
display(check_outlier(resident_seoul_clean))
print("\n=== 상주인구-자치구 ===")
display(check_outlier(resident_gu_clean))
print("\n=== 상주인구-행정동 ===")
display(check_outlier(resident_dong_clean))
print("\n=== 영역-상권 ===")
display(check_outlier(area_clean))

=== 점포-상권 ===

        컬럼명  이상치후보수  하한값   상한값
0       점포수   29493 -5.0  11.0
1   유사업종점포수   32765 -5.0  11.0
2       개업률   26581  0.0   0.0
3     개업점포수   26716  0.0   0.0
4       폐업률   30246  0.0   0.0
5     폐업점포수   32379  0.0   0.0
6  프랜차이즈점포수   54489  0.0   0.0

=== 상권변화지표-상권 ===

          컬럼명  이상치후보수   하한값    상한값
0    운영영업개월평균    1588  53.5  161.5
1    폐업영업개월평균    1990  33.5   69.5
2  서울운영영업개월평균       0  78.5  130.5
3  서울폐업영업개월평균       0  47.0   55.0

=== 2023년-추정매출-상권 ===

            컬럼명  이상치후보수           하한값           상한값
0        당월매출금액   10605 -8.204772e+08  1.493827e+09
1        당월매출건수   12403 -3.190150e+04  5.539050e+04
2        주중매출금액   10657 -6.214517e+08  1.129463e+09
3        주말매출금액   10725 -1.880925e+08  3.328056e+08
4       월요일매출금액   10841 -1.201599e+08  2.145009e+08
5       화요일매출금액   10743 -1.225089e+08  2.190686e+08
6       수요일매출금액   10786 -1.230069e+08  2.211406e+08
7       목요일매출금액   10655 -1.232410e+08  2.210679e+08
8       금요일매출금액   10796 -1.343333e+08  2.410241e+08
9       토요일매출금액   10666 -1.193127e+08  2.112145e+08
10      일요일매출금액   11297 -6.870030e+07  1.145005e+08
11  시간대0006매출금액   17946 -4.978701e+06  8.297835e+06
12  시간대0611매출금액   12495 -6.528419e+07  1.092223e+08
13  시간대1114매출금액   11198 -1.985794e+08  3.454535e+08
14  시간대1417매출금액   11165 -1.739265e+08  3.100228e+08
15  시간대1721매출금액   10670 -2.295471e+08  4.134500e+08
16  시간대2124매출금액   12776 -5.622713e+07  9.371188e+07
17       남성매출금액   10777 -3.866977e+08  6.952816e+08
18       여성매출금액   10935 -3.501876e+08  6.304730e+08
19    연령대10매출금액   13143 -2.975919e+06  4.959864e+06
20    연령대20매출금액   11806 -7.861496e+07  1.340151e+08
21    연령대30매출금액   11030 -1.425819e+08  2.498589e+08
22    연령대40매출금액   10662 -1.661168e+08  2.970636e+08
23    연령대50매출금액   10783 -1.646646e+08  2.967247e+08
24  연령대60이상매출금액   12243 -1.298929e+08  2.285156e+08
25       주중매출건수   12300 -2.396450e+04  4.163150e+04
26       주말매출건수   12528 -7.578000e+03  1.301400e+04
27      월요일매출건수   12474 -4.682500e+03  8.097500e+03
28      화요일매출건수   12324 -4.681000e+03  8.103000e+03
29      수요일매출건수   12272 -4.763000e+03  8.261000e+03
30      목요일매출건수   12241 -4.761125e+03  8.249875e+03
31      금요일매출건수   12211 -5.144500e+03  8.921500e+03
32      토요일매출건수   12342 -4.564000e+03  7.868000e+03
33      일요일매출건수   13215 -2.862000e+03  4.770000e+03
34  시간대건수06매출건수   17653 -1.305000e+02  2.175000e+02
35  시간대건수11매출건수   14799 -2.657000e+03  4.447000e+03
36  시간대건수14매출건수   11888 -8.407000e+03  1.428900e+04
37  시간대건수17매출건수   12323 -6.420000e+03  1.113200e+04
38  시간대건수21매출건수   12164 -8.899125e+03  1.541588e+04
39  시간대건수24매출건수   14701 -1.665000e+03  2.775000e+03
40       남성매출건수   12574 -1.564350e+04  2.708050e+04
41       여성매출건수   12433 -1.437062e+04  2.482038e+04
42    연령대10매출건수   14528 -2.220000e+02  3.700000e+02
43    연령대20매출건수   13514 -4.117500e+03  6.958500e+03
44    연령대30매출건수   12879 -6.251000e+03  1.070100e+04
45    연령대40매출건수   12538 -6.002500e+03  1.043350e+04
46    연령대50매출건수   12241 -6.113125e+03  1.062588e+04
47  연령대60이상매출건수   12479 -4.725625e+03  8.145375e+03

=== 2024년-추정매출-상권 ===

            컬럼명  이상치후보수           하한값           상한값
0        당월매출금액   10689 -8.201603e+08  1.492416e+09
1        당월매출건수   12268 -3.137725e+04  5.446875e+04
2        주중매출금액   10774 -6.222642e+08  1.130065e+09
3        주말매출금액   10813 -1.869760e+08  3.305064e+08
4       월요일매출금액   10984 -1.218158e+08  2.171721e+08
5       화요일매출금액   10801 -1.253893e+08  2.240431e+08
6       수요일매출금액   10729 -1.200189e+08  2.152972e+08
7       목요일매출금액   10787 -1.219464e+08  2.186613e+08
8       금요일매출금액   10843 -1.350435e+08  2.421811e+08
9       토요일매출금액   10799 -1.186554e+08  2.100226e+08
10      일요일매출금액   11182 -6.791742e+07  1.131957e+08
11  시간대0006매출금액   17790 -5.258762e+06  8.764602e+06
12  시간대0611매출금액   12371 -6.784454e+07  1.136521e+08
13  시간대1114매출금액   11349 -1.998076e+08  3.478020e+08
14  시간대1417매출금액   11217 -1.718460e+08  3.064227e+08
15  시간대1721매출금액   10742 -2.254594e+08  4.050953e+08
16  시간대2124매출금액   12641 -5.414148e+07  9.023580e+07
17       남성매출금액   10732 -3.876061e+08  6.960199e+08
18       여성매출금액   11074 -3.480080e+08  6.259746e+08
19    연령대10매출금액   13205 -2.547395e+06  4.245659e+06
20    연령대20매출금액   11720 -7.051176e+07  1.198903e+08
21    연령대30매출금액   10987 -1.407190e+08  2.461116e+08
22    연령대40매출금액   10757 -1.609685e+08  2.867820e+08
23    연령대50매출금액   10725 -1.680064e+08  3.019516e+08
24  연령대60이상매출금액   12041 -1.428307e+08  2.512840e+08
25       주중매출건수   12282 -2.357325e+04  4.094475e+04
26       주말매출건수   12380 -7.470000e+03  1.281800e+04
27      월요일매출건수   12416 -4.659000e+03  8.053000e+03
28      화요일매출건수   12209 -4.720750e+03  8.169250e+03
29      수요일매출건수   12130 -4.567000e+03  7.913000e+03
30      목요일매출건수   12211 -4.674000e+03  8.094000e+03
31      금요일매출건수   12135 -5.088000e+03  8.816000e+03
32      토요일매출건수   12229 -4.499500e+03  7.752500e+03
33      일요일매출건수   12984 -2.829000e+03  4.715000e+03
34  시간대건수06매출건수   17548 -1.320000e+02  2.200000e+02
35  시간대건수11매출건수   14646 -2.711500e+03  4.540500e+03
36  시간대건수14매출건수   11762 -8.452250e+03  1.436975e+04
37  시간대건수17매출건수   12283 -6.361000e+03  1.103100e+04
38  시간대건수21매출건수   12155 -8.593750e+03  1.487225e+04
39  시간대건수24매출건수   14655 -1.576500e+03  2.627500e+03
40       남성매출건수   12326 -1.552950e+04  2.685850e+04
41       여성매출건수   12336 -1.426075e+04  2.460525e+04
42    연령대10매출건수   14188 -1.950000e+02  3.250000e+02
43    연령대20매출건수   13421 -3.655750e+03  6.170250e+03
44    연령대30매출건수   12611 -6.216000e+03  1.062400e+04
45    연령대40매출건수   12381 -5.821500e+03  1.010250e+04
46    연령대50매출건수   12121 -6.211750e+03  1.077425e+04
47  연령대60이상매출건수   12365 -5.207750e+03  8.970250e+03

=== 2025년-추정매출-상권 ===

            컬럼명  이상치후보수           하한값           상한값
0        당월매출금액   10779 -8.093484e+08  1.471149e+09
1        당월매출건수   12197 -3.043338e+04  5.277562e+04
2        주중매출금액   10725 -6.159814e+08  1.116706e+09
3        주말매출금액   10830 -1.884923e+08  3.331549e+08
4       월요일매출금액   10880 -1.202788e+08  2.141208e+08
5       화요일매출금액   10723 -1.210399e+08  2.158372e+08
6       수요일매출금액   10697 -1.227087e+08  2.194913e+08
7       목요일매출금액   10764 -1.204460e+08  2.157432e+08
8       금요일매출금액   10771 -1.344882e+08  2.405828e+08
9       토요일매출금액   10771 -1.197315e+08  2.116933e+08
10      일요일매출금액   11167 -6.875722e+07  1.145954e+08
11  시간대0006매출금액   17515 -4.881204e+06  8.135340e+06
12  시간대0611매출금액   12275 -6.934315e+07  1.161580e+08
13  시간대1114매출금액   11228 -2.024517e+08  3.521610e+08
14  시간대1417매출금액   11218 -1.723593e+08  3.070040e+08
15  시간대1721매출금액   10799 -2.221910e+08  3.983310e+08
16  시간대2124매출금액   12545 -5.178796e+07  8.631327e+07
17       남성매출금액   10728 -3.838140e+08  6.884374e+08
18       여성매출금액   10860 -3.475465e+08  6.243299e+08
19    연령대10매출금액   13076 -2.332371e+06  3.887286e+06
20    연령대20매출금액   11606 -6.419216e+07  1.089573e+08
21    연령대30매출금액   10924 -1.372440e+08  2.393590e+08
22    연령대40매출금액   10639 -1.588566e+08  2.817505e+08
23    연령대50매출금액   10696 -1.664611e+08  2.984261e+08
24  연령대60이상매출금액   11776 -1.544479e+08  2.717845e+08
25       주중매출건수   12188 -2.282138e+04  3.959562e+04
26       주말매출건수   12308 -7.305750e+03  1.252825e+04
27      월요일매출건수   12218 -4.492500e+03  7.759500e+03
28      화요일매출건수   12094 -4.446500e+03  7.685500e+03
29      수요일매출건수   12099 -4.529000e+03  7.839000e+03
30      목요일매출건수   12193 -4.515875e+03  7.817125e+03
31      금요일매출건수   12080 -4.886500e+03  8.461500e+03
32      토요일매출건수   12136 -4.398500e+03  7.573500e+03
33      일요일매출건수   12896 -2.767500e+03  4.612500e+03
34  시간대건수06매출건수   17316 -1.215000e+02  2.025000e+02
35  시간대건수11매출건수   14442 -2.696500e+03  4.515500e+03
36  시간대건수14매출건수   11631 -8.324500e+03  1.415150e+04
37  시간대건수17매출건수   12150 -6.238000e+03  1.081000e+04
38  시간대건수21매출건수   12149 -8.128875e+03  1.406012e+04
39  시간대건수24매출건수   14456 -1.437375e+03  2.395625e+03
40       남성매출건수   12281 -1.489800e+04  2.575000e+04
41       여성매출건수   12094 -1.397188e+04  2.408912e+04
42    연령대10매출건수   14004 -1.710000e+02  2.850000e+02
43    연령대20매출건수   13242 -3.223875e+03  5.437125e+03
44    연령대30매출건수   12475 -5.834500e+03  9.961500e+03
45    연령대40매출건수   12310 -5.491000e+03  9.509000e+03
46    연령대50매출건수   12095 -6.059000e+03  1.049300e+04
47  연령대60이상매출건수   12265 -5.610875e+03  9.650125e+03

=== 추정매출-상권배후지 ===

             컬럼명  이상치후보수           하한값           상한값
0         당월매출금액   18319 -9.054961e+08  1.649149e+09
1         당월매출건수   22719 -3.203350e+04  5.545850e+04
2         주중매출금액   18452 -6.885322e+08  1.253022e+09
3         주말매출금액   17873 -2.152210e+08  3.787884e+08
4        월요일매출금액   18883 -1.356340e+08  2.421873e+08
5        화요일매출금액   18527 -1.362641e+08  2.435391e+08
6        수요일매출금액   18412 -1.367960e+08  2.451002e+08
7        목요일매출금액   18336 -1.342955e+08  2.406408e+08
8        금요일매출금액   18582 -1.504937e+08  2.688941e+08
9        토요일매출금액   17925 -1.384052e+08  2.437804e+08
10       일요일매출금액   18778 -7.392711e+07  1.232119e+08
11  시간대00~06매출금액   30554 -3.881788e+06  6.469648e+06
12  시간대06~11매출금액   20652 -9.389422e+07  1.579027e+08
13  시간대11~14매출금액   18365 -2.244431e+08  3.905937e+08
14  시간대14~17매출금액   18333 -2.179431e+08  3.877574e+08
15  시간대17~21매출금액   17565 -2.381618e+08  4.285531e+08
16  시간대21~24매출금액   22975 -4.468676e+07  7.447794e+07
17        남성매출금액   18756 -4.293715e+08  7.711673e+08
18        여성매출금액   18517 -4.080561e+08  7.288461e+08
19     연령대10매출금액   22075 -2.718572e+06  4.530954e+06
20     연령대20매출금액   20145 -6.575276e+07  1.113436e+08
21     연령대30매출금액   18767 -1.444178e+08  2.514576e+08
22     연령대40매출금액   18315 -1.795346e+08  3.170016e+08
23     연령대50매출금액   18253 -1.998855e+08  3.570222e+08
24   연령대60이상매출금액   20752 -1.927179e+08  3.394242e+08
25        주중매출건수   22695 -2.376525e+04  4.120875e+04
26        주말매출건수   22383 -8.052000e+03  1.375600e+04
27       월요일매출건수   23114 -4.607750e+03  7.970250e+03
28       화요일매출건수   22639 -4.647000e+03  8.033000e+03
29       수요일매출건수   22591 -4.724000e+03  8.172000e+03
30       목요일매출건수   22676 -4.711500e+03  8.148500e+03
31       금요일매출건수   22424 -5.157500e+03  8.910500e+03
32       토요일매출건수   22125 -4.955000e+03  8.493000e+03
33       일요일매출건수   23192 -2.836500e+03  4.727500e+03
34  시간대00~06매출건수   30660 -1.065000e+02  1.775000e+02
35  시간대06~11매출건수   24956 -3.191500e+03  5.356500e+03
36  시간대11~14매출건수   21943 -8.426500e+03  1.433750e+04
37  시간대14~17매출건수   22167 -7.251500e+03  1.256050e+04
38  시간대17~21매출건수   21815 -8.766250e+03  1.512775e+04
39  시간대21~24매출건수   26178 -1.318500e+03  2.197500e+03
40        남성매출건수   22644 -1.548225e+04  2.671575e+04
41        여성매출건수   22708 -1.514775e+04  2.603825e+04
42     연령대10매출건수   25003 -1.935000e+02  3.225000e+02
43     연령대20매출건수   24172 -3.150000e+03  5.306000e+03
44     연령대30매출건수   23616 -5.624250e+03  9.597750e+03
45     연령대40매출건수   22991 -5.633000e+03  9.735000e+03
46     연령대50매출건수   22541 -6.581250e+03  1.136075e+04
47   연령대60이상매출건수   22776 -6.760000e+03  1.159200e+04

=== 길단위인구-상권 ===

             컬럼명  이상치후보수        하한값        상한값
0         총유동인구수    1599 -1145702.0  2499234.0
1        남성유동인구수    1650  -535735.5  1176276.5
2        여성유동인구수    1626  -601870.5  1310525.5
3     연령대10유동인구수    1845  -154302.5   324909.5
4     연령대20유동인구수    2477  -193674.5   406737.5
5     연령대30유동인구수    2380  -190265.5   412890.5
6     연령대40유동인구수    1988  -177770.0   393438.0
7     연령대50유동인구수    1526  -167951.5   368684.5
8   연령대60이상유동인구수    1631  -245487.5   531948.5
9   시간대0006유동인구수    1665  -293490.5   617721.5
10  시간대0611유동인구수    1559  -234310.5   512461.5
11  시간대1114유동인구수    1920  -138847.5   306732.5
12  시간대1417유동인구수    1949  -138459.5   306952.5
13  시간대1721유동인구수    1718  -192450.0   423238.0
14  시간대2124유동인구수    1701  -144728.0   310616.0
15      월요일유동인구수    1601  -165085.5   359366.5
16      화요일유동인구수    1634  -165609.5   360538.5
17      수요일유동인구수    1648  -165720.0   360968.0
18      목요일유동인구수    1666  -165447.5   360700.5
19      금요일유동인구수    1652  -164685.5   359398.5
20      토요일유동인구수    1631  -161445.0   351483.0
21      일요일유동인구수    1658  -160130.5   347473.5

=== 상주인구-상권 ===

               컬럼명  이상치후보수     하한값     상한값
0           총상주인구수    1674 -3303.5  7212.5
1          남성상주인구수    1677 -1614.0  3538.0
2          여성상주인구수    1604 -1716.5  3719.5
3       연령대10상주인구수    1919  -339.0   701.0
4       연령대20상주인구수    2077  -572.5  1191.5
5       연령대30상주인구수    1883  -595.5  1248.5
6       연령대40상주인구수    1869  -485.5  1038.5
7       연령대50상주인구수    1770  -536.0  1144.0
8     연령대60이상상주인구수    1811  -877.5  1902.5
9     남성연령대10상주인구수    1873  -173.5   358.5
10    남성연령대20상주인구수    1930  -270.5   565.5
11    남성연령대30상주인구수    1886  -304.0   640.0
12    남성연령대40상주인구수    1929  -240.5   523.5
13    남성연령대50상주인구수    1710  -263.0   569.0
14  남성연령대60이상상주인구수    1879  -395.5   864.5
15    여성연령대10상주인구수    1890  -165.5   342.5
16    여성연령대20상주인구수    2289  -301.0   619.0
17    여성연령대30상주인구수    2074  -282.5   593.5
18    여성연령대40상주인구수    1736  -242.0   510.0
19    여성연령대50상주인구수    1789  -271.5   572.5
20  여성연령대60이상상주인구수    1717  -486.0  1042.0
21            총가구수    1628 -1819.0  4005.0
22          아파트가구수       0     0.0     0.0
23         비아파트가구수    1628 -1819.0  4005.0

=== 상주인구-상권배후지 ===

               컬럼명  이상치후보수       하한값        상한값
0           총상주인구수     323 -5666.500  31153.500
1          남성상주인구수     342 -2784.375  15208.625
2          여성상주인구수     323 -2896.500  15979.500
3       연령대10상주인구수     428  -929.000   3815.000
4       연령대20상주인구수     759 -1075.500   4736.500
5       연령대30상주인구수     619 -1013.000   4955.000
6       연령대40상주인구수     461  -871.000   4593.000
7       연령대50상주인구수     386  -999.500   5036.500
8     연령대60이상상주인구수     286 -2019.625   8757.375
9     남성연령대10상주인구수     472  -470.500   1949.500
10    남성연령대20상주인구수     753  -506.000   2278.000
11    남성연령대30상주인구수     657  -518.000   2514.000
12    남성연령대40상주인구수     452  -446.000   2338.000
13    남성연령대50상주인구수     404  -463.000   2465.000
14  남성연령대60이상상주인구수     303  -889.000   3943.000
15    여성연령대10상주인구수     453  -455.500   1868.500
16    여성연령대20상주인구수     861  -580.000   2452.000
17    여성연령대30상주인구수     572  -497.125   2427.875
18    여성연령대40상주인구수     472  -460.500   2295.500
19    여성연령대50상주인구수     367  -540.000   2572.000
20  여성연령대60이상상주인구수     280 -1128.500   4803.500
21            총가구수     363 -3028.000  15678.000
22          아파트가구수       0     0.000      0.000
23         비아파트가구수     363 -3028.000  15678.000

=== 상주인구-서울시 ===

               컬럼명  이상치후보수        하한값         상한값
0           총상주인구수       0  8904587.5  10120143.5
1          남성상주인구수       0  4269887.5   4957323.5
2          여성상주인구수       0  4634700.0   5162820.0
3       연령대10상주인구수       0  1001443.5   1647471.5
4       연령대20상주인구수       4  1185751.5   1623987.5
5       연령대30상주인구수       0  1341660.5   1554992.5
6       연령대40상주인구수       0  1249592.5   1694476.5
7       연령대50상주인구수       0  1446927.0   1568159.0
8     연령대60이상상주인구수       0  2031056.5   2679212.5
9     남성연령대10상주인구수       0   511081.0    847529.0
10    남성연령대20상주인구수       0   541337.5    807109.5
11    남성연령대30상주인구수       0   670835.0    778051.0
12    남성연령대40상주인구수       0   617863.5    839859.5
13    남성연령대50상주인구수       0   710588.5    770400.5
14  남성연령대60이상상주인구수       4   914374.0   1218182.0
15    여성연령대10상주인구수       0   490362.5    799942.5
16    여성연령대20상주인구수       4   644414.0    816878.0
17    여성연령대30상주인구수       0   670825.5    776941.5
18    여성연령대40상주인구수       0   631729.0    854617.0
19    여성연령대50상주인구수       0   736338.5    797758.5
20  여성연령대60이상상주인구수       0  1116682.5   1461030.5
21            총가구수       0  4352703.5   4514483.5
22          아파트가구수       0        0.0         0.0
23         비아파트가구수       0  4352703.5   4514483.5

=== 상주인구-자치구 ===

               컬럼명  이상치후보수        하한값         상한값
0           총상주인구수       0  76865.000  689057.000
1          남성상주인구수       0  36438.500  335458.500
2          여성상주인구수       0  44613.500  346849.500
3       연령대10상주인구수       0  -9602.000  116662.000
4       연령대20상주인구수      18   4359.250  100289.250
5       연령대30상주인구수      29  12710.000   98438.000
6       연령대40상주인구수       0   3840.500  113636.500
7       연령대50상주인구수       0  17356.000  105028.000
8     연령대60이상상주인구수       0  25402.625  171577.625
9     남성연령대10상주인구수       0  -5599.750   61290.250
10    남성연령대20상주인구수      18   3367.500   47011.500
11    남성연령대30상주인구수      40   6365.500   48129.500
12    남성연령대40상주인구수       0   2466.000   56082.000
13    남성연령대50상주인구수       4   9393.500   50573.500
14  남성연령대60이상상주인구수       0   8297.750   80331.750
15    여성연령대10상주인구수       0  -4306.750   55879.250
16    여성연령대20상주인구수      18    399.375   52496.375
17    여성연령대30상주인구수      18   5628.500   51016.500
18    여성연령대40상주인구수       0   -455.500   60604.500
19    여성연령대50상주인구수       0   7962.500   54454.500
20  여성연령대60이상상주인구수       0  15105.000   92385.000
21            총가구수       0  54687.000  291351.000
22          아파트가구수       0      0.000       0.000
23         비아파트가구수       0  54687.000  291351.000

=== 상주인구-행정동 ===

               컬럼명  이상치후보수       하한값        상한값
0           총상주인구수     202  -387.750  44206.250
1          남성상주인구수     144  -411.000  21669.000
2          여성상주인구수     187  -137.000  22823.000
3       연령대10상주인구수     468 -1434.500   7017.500
4       연령대20상주인구수     249  -814.500   6901.500
5       연령대30상주인구수     162  -736.125   7370.875
6       연령대40상주인구수     290  -540.125   7286.875
7       연령대50상주인구수      89  -321.000   7359.000
8     연령대60이상상주인구수     138  -277.500  11542.500
9     남성연령대10상주인구수     504  -671.750   3518.250
10    남성연령대20상주인구수     235  -292.000   3228.000
11    남성연령대30상주인구수     191  -394.500   3689.500
12    남성연령대40상주인구수     309  -155.500   3512.500
13    남성연령대50상주인구수      68  -165.500   3622.500
14  남성연령대60이상상주인구수     113  -151.625   5231.375
15    여성연령대10상주인구수     479  -681.000   3399.000
16    여성연령대20상주인구수     299  -531.250   3650.750
17    여성연령대30상주인구수     227  -373.250   3680.750
18    여성연령대40상주인구수     297  -434.375   3788.625
19    여성연령대50상주인구수     100  -185.875   3761.125
20  여성연령대60이상상주인구수     127  -221.000   6371.000
21            총가구수     198  -428.000  20852.000
22          아파트가구수       0     0.000      0.000
23         비아파트가구수     198  -428.000  20852.000

=== 영역-상권 ===

     컬럼명  이상치후보수         하한값         상한값
0  엑스좌표값       0  175488.750  221692.750
1  와이좌표값       0  432601.000  466141.000
2   영역면적      82 -103895.875  267373.125

# 분석 변수 정리

In [19]:
# 병합 및 식별에 사용할 컬럼
key_cols = [ '기준년분기코드', '상권코드']

# 업종 단위 데이터에서 사용할 컬럼
industry_key = [ '서비스업종코드' ]

# 공간 단위별 식별 컬럼
trade_key = ['기준년분기코드', '상권코드']
background_key = ['기준년분기코드', '상권배후지코드']
seoul_key = ['기준년분기코드', '서울시코드']
gu_key = ['기준년분기코드', '자치구코드']
dong_key = ['기준년분기코드', '행정동코드']
area_key = ['상권코드']

# 전처리 결과 및 최종 검증

In [20]:
datasets = {
    '점포-상권': store_clean,
    '상권변화지표-상권': change_clean,
    '2023년-추정매출-상권': sales_2023,
    '2024년-추정매출-상권': sales_2024,
    '2025년-추정매출-상권': sales_2025,
    '추정매출-상권배후지': sales_bg_clean,
    '길단위인구-상권': floating_clean,
    '상주인구-상권': resident_trade_clean,
    '상주인구-상권배후지': resident_bg_clean,
    '상주인구-서울시': resident_seoul_clean,
    '상주인구-자치구': resident_gu_clean,
    '상주인구-행정동': resident_dong_clean,
    '영역-상권': area_clean
}

for name, df in datasets.items():

    print(f"===== {name} =====")
    print("데이터 크기:", df.shape)
    print("결측치:",
        df.isnull().sum().sum()
    )
    print("중복값:",
        df.duplicated().sum()
    )
    
print()

===== 점포-상권 =====
데이터 크기: (304775, 14)
결측치: 0
중복값: 0
===== 상권변화지표-상권 =====
데이터 크기: (36300, 11)
결측치: 0
중복값: 0
===== 2023년-추정매출-상권 =====
데이터 크기: (88246, 55)
결측치: 0
중복값: 0
===== 2024년-추정매출-상권 =====
데이터 크기: (87179, 55)
결측치: 0
중복값: 0
===== 2025년-추정매출-상권 =====
데이터 크기: (85732, 55)
결측치: 0
중복값: 0
===== 추정매출-상권배후지 =====
데이터 크기: (147035, 55)
결측치: 0
중복값: 0
===== 길단위인구-상권 =====
데이터 크기: (36281, 27)
결측치: 0
중복값: 0
===== 상주인구-상권 =====
데이터 크기: (35908, 29)
결측치: 0
중복값: 0
===== 상주인구-상권배후지 =====
데이터 크기: (23980, 29)
결측치: 0
중복값: 0
===== 상주인구-서울시 =====
데이터 크기: (22, 27)
결측치: 0
중복값: 0
===== 상주인구-자치구 =====
데이터 크기: (550, 27)
결측치: 0
중복값: 0
===== 상주인구-행정동 =====
데이터 크기: (9350, 27)
결측치: 0
중복값: 0
===== 영역-상권 =====
데이터 크기: (1650, 11)
결측치: 0
중복값: 0

In [22]:
# 전처리 완료 데이터 저장
store_clean.to_csv('점포-상권_전처리완료.csv', index=False, encoding='utf-8-sig')
change_clean.to_csv('상권변화지표-상권_전처리완료.csv', index=False, encoding='utf-8-sig')

sales_2023.to_csv('2023년-추정매출-상권_전처리완료.csv', index=False, encoding='utf-8-sig')
sales_2024.to_csv('2024년-추정매출-상권_전처리완료.csv', index=False, encoding='utf-8-sig')
sales_2025.to_csv('2025년-추정매출-상권_전처리완료.csv', index=False, encoding='utf-8-sig')

sales_bg_clean.to_csv('추정매출-상권배후지_전처리완료.csv', index=False, encoding='utf-8-sig')

floating_clean.to_csv('길단위인구-상권_전처리완료.csv', index=False, encoding='utf-8-sig')

resident_trade_clean.to_csv('상주인구-상권_전처리완료.csv', index=False, encoding='utf-8-sig')
resident_bg_clean.to_csv('상주인구-상권배후지_전처리완료.csv', index=False, encoding='utf-8-sig')
resident_seoul_clean.to_csv('상주인구-서울시_전처리완료.csv', index=False, encoding='utf-8-sig')
resident_gu_clean.to_csv('상주인구-자치구_전처리완료.csv', index=False, encoding='utf-8-sig')
resident_dong_clean.to_csv('상주인구-행정동_전처리완료.csv', index=False, encoding='utf-8-sig')

area_clean.to_csv('영역-상권_전처리완료.csv', index=False, encoding='utf-8-sig')

print("전처리 완료 데이터 저장 완료")

전처리 완료 데이터 저장 완료